export class OddanieTexts {
  // --- html ---
static dzien0: string = `
<b>Dzień oddania się Panu Jezusowi przez Maryję w Niewolę Miłości</b><br>
Nasz duchowy mistrz, św. Ludwik, do końca swoich dni żył nabożeństwem do Najświętszej Maryi Panny i oddaniem się Jej w Niewolę Miłości i tego nauczał innych. Fundament tego nabożeństwa odnalazł w Ewangelii i woli Pana Jezusa, który z wysokości krzyża wypowiada słowa: „«Niewiasto, oto syn Twój». Następnie rzekł do ucznia: «Oto Matka twoja». I od tej godziny uczeń wziął Ją do siebie" (J 19,25-26). Maryja jest Jezusowym darem dla każdego z Nas. Matką Boga i Matką każdego człowieka. Św. Ludwik był i jest echem głosu Chrystusa wołającego z krzyża. Spotykał tysiące ludzi, często biednych, bez żadnej nadziei i zachęcał ich, aby całkowicie oddawali się Maryi jako Niewolnicy Miłości, a przez Nią Panu Jezusowi. Św. Ludwik o Niewoli Miłości pisze tak:<br>
<i>„[Należymy do Jezusa Chrystusa i do Maryi jako niewolnicy.] (...) nie należymy do samych siebie, jak mówi Apostoł (1 Kor 16,9), lecz całkowicie do Chrystusa jako Jego członki i Jego niewolnicy, których odkupił nieskończenie drogo, bo za cenę swojej drogocennej Krwi (1 P 1,19). Przed chrztem św. byliśmy niewolnikami szatana. Chrzest św. uczynił nas prawdziwymi niewolnikami Jezusa Chrystusa; którzy mają żyć, pracować i umierać tylko po to, by rodzić owoc Bogu-człowiekowi (por. Rz 7,4), by Go wielbić w naszym ciele i pozwolić Mu panować w naszej duszy, gdyż jesteśmy Jego zdobyczą, Jego ludem nabytym i Jego dziedzictwem (por. 1 P 2,9)"</i>(św. Ludwik, Traktat...,68).<br>
<i>„Niewola dobrowolna jest najdoskonalsza i przynosi najwięcej chwały Bogu, który patrzy w serce (zob. 1Sm 16,7), prosi o serce (zob. Prz 23,26) i nazywa się Bogiem serca (zob. Ps 73,26), czyli miłującej Go woli. Przez dobrowolną bowiem niewolę przenosi człowiek Boga i Jego służbę ponad wszystko, choćby nawet prawem natury nie był do tego zobowiązany" (św. Ludwik, Traktat.., 70).</i>
<i>„(...) z miłości i dobrej woli. I to właśnie jest niewola, w którą mamy siebie oddać Bogu przez Maryję, w najdoskonalszy sposób, jakim tylko stworzenie posłużyć się może, by powierzyć się swojemu Stwórcy"</i> (św. Ludwik, Tajemnica Maryi, 32).<br>
Jeszcze raz przypomnijmy sobie słowa Św. Jan Pawła II: „Znaczenie słowa «niewola», tak dotkliwie dla Polaków, kryje w sobie podobny paradoks, jak słowa Ewangelii o własnym życiu, które trzeba stracić, ażeby je zyskać (por. Mt 10, 39). Wolność jest wielkim darem Bożym. Trzeba go dobrze używać. Miłość stanowi spełnienie wolności, a równocześnie do jej istoty należy przynależeć, czyli - nie być wolnym ale raczej - być wolnym w sposób dojrzały! Jednakże tego «niebycia wolnym» w miłości, nigdy nie odczuwa się jako niewolę. Nie odczuwa jako niewolę matka, że jest uwiązana przy chorym dziecku, lecz jako afirmację swojej wolności, jako jej spełnienie. Wtedy jest najbardziej wolna! Oddanie w niewolę wskazuje więc na «szczególną zależność», na świętą zależność i na «bezwzględną ufność». Bez tej zależności świętej, bez tej ufności heroicznej, życie ludzkie jest nijakie!" (św. Jan Paweł II w czasie I pielgrzymki do Polski, str 18/19)<br>
Pierwszym Niewolnikiem Miłości jest sam Panu Jezus o którym św. Ludwik pisze tak: „Jezus, nasz wielki Przyjaciel, oddał się nam bez zastrzeżeń, z duszą i ciałem, z cnotami, łaskami i zasługami: Zdobył mnie całego - mówi św. Bernard - oddając mi się całkowicie. Czyż nie jest wymogiem sprawiedliwości i wdzięczności, byśmy dali Jezusowi wszystko, co dać możemy? Wszak to Jezus pierwszy był wobec nas hojny. Idźmy za Nim, a doznamy w życiu, w godzinę śmierci i w wieczności jeszcze większej Jego szczodrobliwości" (św. Ludwik, Traktat..., 138).<br>
Bóg, Bóg-człowiek, Jezus Chrystus, mocą Ducha Świętego wstąpił do łona swojej Matki jako małe, bezbronne dziecko, we wszystkim zależne od Niej. Pan wszystkiego, Król królów oddaje się Maryi i nam całkowicie. Do dzisiaj pozostaje z nami jako Niewolnik Miłości w małej, białej hostii. Na głos kapłana zstępuje na ołtarze całego świata, podczas każdej Mszy Świętej, aby nam powiedzieć: Jestem cały Twój.<br>
Wierną uczennicą Chrystusa jest Maryja. Na wezwanie nieba, które przynosi anioł, odpowiada: TAK! Oddaje się Stwórcy bez reszty, aby być całkowicie Jego i dla Niego. <i>„Oto ja służebnica Pańska. Niech mi się stanie według Twojego Słowa!"</i> (Łk 1,38) i można tutaj dopowiedzieć za św. Pawłem: „Teraz zaś już nie ja żyję, lecz żyje we mnie Chrystus" (Ga 2,20). Odpowiedź Maryi na słowa anioła można przetłumaczyć <i>„Oto niewolnica Pana! Oby mi się stało (zdarzyło) tak, jak chce Bóg!".</i>
Słowo FIAT, niech mi się stanie, zmieniło całą historię ludzkości, słowo, na które Bóg zstępuje na ziemię i dokonuje się największy cud mocy działania Ducha Świętego. Bóg począł się w łonie Maryi za sprawą Ducha Świętego! Zaczyna się nowa historia ludzkości. Nowa historia każdego z Nas. Maryja staje się Matką Boga. Maryja, która zostaje ogłoszona Królową Nieba i ziemi. Maryja, której Niepokalane Serce Zwycięży, przychodzi dzisiaj do każdego z nas.<br>
Karol Wojtyła, który traci całą swoją rodzinę, można powiedzieć, że po ludzku traci wszystko. Wówczas w jego ręce trafia Traktat św. Ludwika, w którym czyta o Świętej Niewoli Miłości: „Zawsze, kiedy przejeżdżam obok tej fabryki (...) staje mi przed oczyma mała książeczka w niebieskiej okładce (...) nosiła tytuł „Traktat o doskonałym nabożeństwie do Najświętszej Maryi Panny", autorem był (...) św. Ludwik Maria Grignion de Montfort. Mała książeczka w niebieskiej okładce, podobna do modlitewnika, była wtedy przeze mnie czytana w ciągu wielu dni i tygodni. (...) Z tej książeczki nauczyłem się, co to właściwie jest nabożeństwo do Matki Bożej. (...) Tak bardzo ją czytałem, że cała była poplamiona sodą, i na okładkach i w środku. Pamiętam dobrze te plamy sody, bo są one ważnym elementem całego mojego życia wewnętrznego" (Karol Wojtyła w kazaniu w Borku Fałęckim 8 listopada 1968 r.). Karol przeżywa swoje rekolekcje, aby na końcu drogi powiedzieć Maryi: Totus Tuus. Cały Jestem Twój. To będzie hasło jego życia. I zaczęło się! Całkowite tak dla Boga przez Maryję. To był początek drogi. Jaka była ta droga? Od Karola z Wadowic, przez kapłana, biskupa, papieża do świętości. Tak Duch Święty przez Maryję zrodził młodego Karola do WIELKIEJ misji.<br>
Kardynał Wyszyński, w więzieniu, w zamknięciu, przeżywa swoje rekolekcje według św. Ludwik Marii Grignion de Montfort. Można powiedzieć, że Bóg zatrzymał wszystko, aby wszedł na tę drogę. Owocem tych więziennych rekolekcji jest osobiste, całkowite oddanie się w niewolę Maryi. Jak wielkich dzieł przez niego Bóg dokonał, można by o tym wiele pisać. Dzisiaj już jest tam, gdzie wzywa Bóg każdego z nas, a jednocześnie nieustannie wstawia się na nami, abyśmy doszli tam, gdzie on już jest, aby Polska nie odeszła od Boga, abyśmy pociągnęli za sobą tych, których Bóg stawia na naszej drodze. <br>
Każdy z nas podobnie, jako Kardynał Wojtyła, Kardynał Wyszyński, Maksymilian Kolbe czy wielu innych świętych, ma przed sobą misję zleconą przez Boga. Jest to nasza WIELKA misja, misja naszego życia, najważniejsza i najcenniejsza, która wydarza się tylko jeden raz. Czy będziemy kimś znanym, czy żyjącym zwyczajnie, w miejscu, gdzie teraz jesteśmy, czy będą to rzeczy spektakularne, czy te drobne, malutkie, pełnione w ukryciu, tak jak żyła Matka Boża - to nie jest istotne. Najważniejsze, aby wszystko i zawsze było oddane Tej, której oddał się sam Bóg!<br>
Dzisiaj po-33 dniowych przygotowaniach na bazie wskazań św. Ludwika stajemy przed decyzją wypowiedzenia naszego FIAT. Stajemy przed Odwieczną Miłością, która pragnie mieć nas całymi. To wielka i doniosła chwila. To doskonałe odnowienie naszych przyrzeczeń chrzcielnych, które już były wielką łaskę, a dzięki którym staliśmy się dziećmi Boga. Dzisiaj pragniemy potwierdzić to przyrzeczenie i wypowiedzieć je raz jeszcze. Jeszcze głębiej. Oddać się całkowicie Maryi, zupełnie i na własności, nic nie zostawiając sobie, zupełnie nic, aby całkowicie należeć do Boga. Oddać wszystko i na zawsze! Jako Niewolnicy z Miłości i dla Miłości.<br><br>Św. Ludwik zachęca nas: „Trzeba wybrać odpowiedni dzień, by się oddać, poświęcić i ofiarować dobrowolnie, z miłości, bez przymusu, całkowicie i bez zastrzeżeń; by ofiarować swoje ciało i duszę; swe dobra zewnętrzne[jak: dom, rodzinę, dochody], jak i dobra wewnętrzne, czyli dotyczące duszy[to znaczy swoje zasługi, łaski, cnoty i zadośćuczynienia]. Zauważyć tu trzeba, że przez to nabożeństwo dusza składa ofiarę Jezusowi przez Maryję ze wszystkiego, co ma najdroższe (...) żeby Ona rozporządzała tym według swojej woli, na największą chwałę Bożą, którą też Ona tylko jedna zna doskonale" (św. Ludwik, Tajemnica Maryi, 29). „Szczęśliwa, po tysiąckroć szczęśliwa jest ta szczodra dusza, która wyzwolona przez Chrzest z tyrańskiej niewoli diabła, oddaje się Jezusowi przez Maryję w niewolę miłości przez Chrzest!" (św. Ludwik, Tajemnica Maryi, 34).<br>
Dzisiaj możesz wypowiedzieć Twoje FIAT, dla Maryi, dla Boga, dla jego Miłującej Woli!<br>
`;

static dzienAkt: string = `
<b>Akt oddania siebie Jezusowi Chrystusowi, Mądrości Wcielonej, przez ręce Maryi</b><br>
   O, odwieczna, Wcielona Mądrości! O, najmilszy i czci najgodniejszy Jezu, prawdziwy Boże i prawdziwy człowiecze, Synu Jednorodzony Ojca Przedwiecznego i Maryi, zawsze Dziewicy! Oddaję Ci najgłębszą cześć w łonie i chwale Twego Ojca w wieczności oraz w dziewiczym łonie Maryi, Twej najgodniejszej Matki, w czasie Twego Wcielenia. Dzięki Ci składam, żeś wyniszczył samego siebie przyjmując postać sługi, by mnie wybawić z okrutnej niewoli szatana. Chwalę Cię i uwielbiam, żeś we wszystkim raczył się poddać Maryi, Twej świętej Matce, aby przez Nią uczynić mnie swym wiernym niewolnikiem. Lecz niestety! W niewdzięczności i niewierności nie dochowałem obietnic uroczyście Tobie złożonych na Chrzcie św. Nie wypełniłem swoich zobowiązań. Nie jestem godzien zwać się dzieckiem czy niewolnikiem Twoim. A ponieważ wszystko we mnie zasługuje na Twój gniew, do Twego Najświętszego i Najdostojniejszego Majestatu nie śmiem już się sam zbliżyć. Przeto uciekam się do wstawiennictwa i miłosierdzia Twej Najświętszej Matki, którą dałeś mi za Pośredniczkę u Siebie. Za Jej możnym pośrednictwem mam nadzieję wyjednać u Ciebie skruchę i przebaczenie mych grzechów oraz prawdziwą mądrość i w niej wytrwanie.<br>
   Pozdrawiam Cię więc, Dziewico Niepokalana, żywy Boga Przybytku, w którym odwieczna, ukryta Mądrość chce odbierać cześć i uwielbienie aniołów i ludzi. Pozdrawiam Cię, Królowo nieba i ziemi, której panowaniu wszystko prócz Boga jest poddane. Pozdrawiam Cię, Ucieczko grzeszników, której miłosierdzie nikogo nie zawiodło. Wysłuchaj mej prośby, pełnej gorącego pragnienia Bożej mądrości, i przyjmij śluby i ofiary, jakie w pokorze Ci składam.<br>
   Ja .................., grzesznik niewierny, odnawiam i zatwierdzam dzisiaj przed Twoim obliczem przyrzeczenia Chrztu św. Wyrzekam się na zawsze szatana, jego pychy i jego dzieł. Całkowicie oddaję się Jezusowi Chrystusowi, Mądrości Wcielonej, aby za Nim iść, niosąc mój krzyż po wszystkie dni życia. Abym zaś był Mu wierniejszy niż dotąd, obieram Ciebie dziś, Maryjo, w obliczu całego Dworu Niebieskiego, za moją Matkę i Panią. Oddaję Ci i poświęcam, jako Twój niewolnik, ciało i duszę swoją, dobra wewnętrzne i zewnętrzne, nawet wartość dobrych moich uczynków, przeszłych, obecnych i przyszłych, pozostawiając Ci całkowite i zupełne prawo rozporządzania mną i wszystkim bez wyjątku, co do mnie należy, według Twego upodobania, ku większej chwale Boga w czasie i wieczności.<br>
   Przyjmij, Panno łaskawa, tę niewielką ofiarę mej niewoli dla uczczenia i naśladowania owej uległości, jaką Mądrość odwieczna Twemu macierzyństwu okazać raczyła; dla uczczenia władzy, jaką Oboje posiadacie nade mną, nikłym robakiem i grzesznikiem nędznym; jako podziękowanie za przywileje, którymi Cię Przenajświętsza Trójca łaskawie obdarzyła. Zapewniam, że odtąd, jako prawdziwy Twój niewolnik, chcę szukać Twojej chwały i Tobie we wszystkim być posłuszny. Matko Przedziwna, przedstaw mnie Twemu drogiemu Synowi jako wiecznego niewolnika, ażeby - jak przez Ciebie mnie odkupił, tak też przez Ciebie przyjąć mnie raczył.<br>
   Matko Miłosierdzia, udziel mi łaski prawdziwej mądrości Bożej i przyjmij mnie do grona tych, których kochasz, pouczasz, prowadzisz, żywisz i bronisz jako dzieci swe i sługi. Dziewico wierna, spraw, abym zawsze i we wszystkim był doskonałym uczniem, naśladowcą i niewolnikiem Mądrości Wcielonej, Jezusa Chrystusa, Syna Twego; abym za Twym pośrednictwem i za Twoim przykładem doszedł do pełni Jego wieku na ziemi i Jego chwały w Niebie. Amen<br>
św. Ludwik Maria Grignion de Montfort, <i>Miłość Mądrości Przedwiecznej</i>, 223-227
`;

}
