export class ThirdWeekTexts {
static modlitwaDoDuchaSw: string = `<b>Modlitwa do Ducha Świętego</b><br><i>Duchu Święty, natchnij mnie. Miłości Boga, pochłoń mnie. Po prawdziwej drodze prowadź mnie, Maryjo, moja Matko, spójrz na mnie, z Jezusem błogosław mnie. Od wszelkiego zła, od wszelkiego złudzenia, od wszelkiego niebezpieczeństwa zachowaj mnie.</i><br>`;
static modlitwaZawierzenia: string = `<b>Modlitwa zawierzenia</b><br><i>Jestem cały Twój i wszystko, co mam, jest Twoją własnością, umiłowany Jezu, przez Maryję, Twoją świętą Matkę. Amen!</i>`;
static tytul: string = '<br><i><b>Tydzień trzeci - Poznanie Pana Jezusa</b></i><br>';  

static dayTitles: { [key: number]: string } = {
  1: 'Dzień 1: Zwiastowanie. Jezus-Słowo Boże. Jezus-Ewangelia',
  2: 'Dzień 2: Boże Narodzenie. Jezus-Dziecko. Jezus-Chleb',
  3: 'Dzień 3: Ofiarowanie w świątyni. Jezus-Prawo Miłości. Jezus-droga do Nieba',
  4: 'Dzień 4: Znalezienie w świątyni. Jezus szukany i znaleziony. Jezus zjednoczony z Ojcem',
  5: 'Dzień 5: Cud przemiany wody wino w Kanie Galilejskiej. Jezus Zbawiciel. Jezus Źródło przemiany',
  6: 'Dzień 6: Ukrzyżowanie. Jezus Król. Jezus MIŁOŚĆ',
  7: 'Dzień 7: Zesłanie Ducha Świętego. Jezus Kościół. Jezus Chrzczący Duchem Świętym'
};

static getDayText(nr: number, body: string = '', withZawierzenie: boolean = false): string {
  const label = ThirdWeekTexts.dayTitles[nr] || `Dzień ${nr}`;
  let result = `${ThirdWeekTexts.tytul}<b>${label}</b><br><br>${ThirdWeekTexts.modlitwaDoDuchaSw}<br>${body}`;
  if (withZawierzenie) {
    result += `<br>${ThirdWeekTexts.modlitwaZawierzenia}`;
  }
  return result;
}

static trescDzien1: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Jezusa Chrystusa, spotkania z Nim w tajemnicy Zwiastowania i odkrycia, że Pan jest w każdym Słowie, które pochodzi z Bożych ust.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„W szóstym miesiącu posłał Bóg anioła Gabriela do miasta w Galilei, zwanego Nazaret, do Dziewicy poślubionej mężowi, imieniem Józef, z rodu Dawida a Dziewicy było na imię Maryja. Wszedłszy do Niej [anioł] i rzekł: «Bądź pozdrowiona, łaski pełna, Pan z Tobą, ». Ona zmieszała się na te słowa i rozważała, co miałoby znaczyć to pozdrowienie. Lecz anioł rzekł do Niej: «Nie bój się, Maryjo, znalazłaś bowiem łaskę u Boga. Oto poczniesz i porodzisz Syna, któremu nadasz imię Jezus. Będzie On wielki i będzie nazwany Synem Najwyższego, a Pan Bóg da Mu tron Jego praojca, Dawida. Będzie panował nad domem Jakuba na wieki, a Jego panowaniu nie będzie końca». Na to Maryja rzekła do anioła: «Jakże się to stanie, skoro nie znam męża?» Anioł Jej odpowiedział: «Duch Święty zstąpi na Ciebie i moc Najwyższego okryje Cię cieniem. Dlatego też Święte, które się narodzi, będzie nazwane Synem Bożym. A oto również krewna Twoja, Elżbieta, poczęła w swej starości syna i jest już w szóstym miesiącu ta, która uchodzi za niepłodną. Dla Boga bowiem nie ma nic niemożliwego». Na to rzekła Maryja: «Oto Ja służebnica Pańska, niech Mi się stanie według słowa twego!» Wtedy odszedł od Niej anioł"</i> (Łk 1,26-38).<br>
<b>Rozważanie</b>
Wejdźmy do nazaretańskiego domku młodej dziewczyny izraelskiej. Ma na imię Miriam. Jest żoną Józefa. Krząta się wokół zwyczajnych zajęć. Dba o dom. Bądźmy z Maryją w tajemnicy codzienności. Zobaczmy, co robi i jak się zachowuje...<br>
Nagle zjawia się z Nieba Boży zwiastun! Miriam słyszy: Bądź pozdrowiona (!), pełna Łaski (!), Pan z Tobą (!), błogosławiona jesteś (!). Czekała na Słowo Boże i doczekała się. Anioł zapowiada przyjście na świat Syna Bożego. Miriam jest poruszona. Przeżywa niepokój, który jest owocem pokory i czci wobec majestatu Stwórcy. Serce Maryi drży... Małżonka Józefa przeczuwa, że nowina, którą przynosi Gabriel oznacza całkowitą nowość... Jestem przekonany, że Miriam nie rozumie wszystkiego. Słucha w milczeniu i zaczyna rozważać Słowo Boże. W sercu młodej Izraelitki rodzi się głęboka modlitwa... Gabriel uspokaja „Nie bój się, Maryjo!" (Łk 1,30). I zaczyna rozjaśniać, co jest Bożym projektem „znalazłaś bowiem łaskę u Boga. Oto poczniesz i porodzisz Syna, któremu nadasz imię Jezus!" (Łk 1,30). Prośmy Maryję, aby wprowadziła nas w to doświadczenie...<br>
Maryja jako Żydówka doskonale zna pierwsze Boże przykazanie obowiązujące każdego członka Narodu Wybranego: „Słuchaj, Izraelu, Pan jest naszym Bogiem - Pan jedynie!" (Pwt 6,4). A zatem pierwsze jest: SŁUCHAJ! W Prologu Janowej Ewangelii czytamy: „Na początku było Słowo..." (J 1,1). A zatem Słowo Boga jest na początku wszystkiego. Jest przed(e) wszystkim i nade wszystko. Ewangelista pisze: „Wszystko przez Nie się stało, a bez Niego nic się nie stało, [z tego], co się stało" (J 1,3). Wszystkie Boże dzieła (cuda) w naszym życiu zaczynają się od Słowa i dzieją się dzięki Słowu, które jest stwórcze, sprawcze, skuteczne i kryje w sobie (wszech)moc Boga. Musimy wiedzieć, że Janowy Prolog to hymn o Słowie, które jest jedno jedyne. Autor czwartej Ewangelii pisze o Słowie Bożym - Jezusie Chrystusie. W Apokalipsie słyszymy, że Jezus ma na imię Słowo Boże „a nazwano Go imieniem Słowo Boga" (Ap 19,13). A więc niewłaściwe jest pytanie: co to jest Biblia (Pismo Święte)? Biblia to Ktoś! To odwieczne Słowo Boga!<br>
Maryja przyjmuje Boże orędzie. Słyszy cztery Słowa (zdania): „[1] Bądź pozdrowiona! [2] Pełna Łaski! [3] Pan z Tobą! [4] Jesteś błogosławiona!". To Słowa - imiona Jezusa. Miriam zaczyna się zastanawiać, co oznacza przyjście Anioła i co chce powiedzieć Stwórca. Wraz z Maryją rozważajmy znaczenie Bożych Słów...<br>
<b>Bądź pozdrowiona!</b> Bóg wita Maryję. I wysyła komunikat: „Widzę Cię! Wiem, że jesteś! Znam Twoje życie!" W języku hebrajskim w pozdrowieniu (przywitaniu) pojawia się słowo <i>Szalom</i> („Pokój Tobie")! A zatem Bóg obdarowuje Maryję pokojem. Słowo Boże (Jezus) jest gwarancją duchowego pokoju. Izajasz, zapowiadając przyjście Mesjasza na świat, pisze, że urodzi się „Książę Pokoju" (zob. Iz 9,5)! Również św. Paweł nazywa Jezusa Pokojem (zob. Ef 2,14). W języku greckim pojawia się tu słówko <i>haire</i>, które oznacza: „Raduj się!". W języku łacińskim pozdrowienie anielskie wyrażamy przy pomocy zwrotu: <i>Ave</i> <i>Maria</i>! Co ciekawe, „Ave" jest odwrotnością imienia Ewa (Ave - Eva)... Jakby Gabriel chciał powiedzieć do Maryi: „Będziesz nową Ewą! Pierwsza okazała się nieposłuszna, ale Ty będziesz zawsze wierna Bogu!".<br>
<b>Pełna Łaski!</b> Św. Łukasz posługuje się tu greckim słowem <i>Kecharitomene, </i>które pod względem gramatycznym jest imiesłowem czasu przeszłego czasownika oznaczającego cudowny dar Bożej Łaski i nadprzyrodzonego piękna (<i>charis</i> oznacza Bożą łaskę, dobroć, życzliwość, ale też piękno, wdzięk, powab, czar, grację). Tak autor natchniony wyraża prawdę o Bożym wybraniu Maryi. Tak określa duchową wspaniałość Miriam z Nazaretu oraz (prze)czystość (przejrzystość, przezroczystość) Niepokalanego Serca, które stanowią cechy wewnętrznego świata Matki Jezusa - właściwości, które stały się bogactwem Maryi na całe życie! Zapewne mamy tu biblijną podstawę dogmatu o Niepokalanym Poczęciu Najświętszej Maryi Panny. Gdy słyszę „Pełna Łaski", widzę Maryję jako najpiękniejsze Boże arcydzieło - Kobietę bez najmniejszego zła, cienia czy skazy, odzianą w Bożą dobroć, utkaną z Miłości... Maryja jest naczyniem w całości napełnionym Bogiem. Pełnia Łaski to wspaniały Boży dar dany Miriam ze względu na przywilej Bożego macierzyństwa. Cała w Bogu... Cała Boża... Powierzająca się Bogu i wyznająca: „Należę do Ciebie! Jestem cała dla Ciebie! Cała Twoja (<i>Tota</i> <i>Tua</i>)!". I tak w dziewiczym łonie małżonki Józefa zaczyna się życie Jezusa - Człowieka. Pełna Łaski oznacza napełniona Jezusem - pełna Jezusowej obecności (miłości).<br>
<b>Pan z Tobą!</b> To jest wprost imię Jezusa. W Księdze Izajasza czytamy zapowiedź przyjścia Zbawiciela na ziemię: „Oto PANNA pocznie i porodzi Syna, i nazwie Go imieniem EMMANUEL" (Iz 7,14). Św. Mateusz doda (przetłumaczy): „...to znaczy: Bóg z nami" (Mt 1,23). Maryja słyszy, że Bóg będzie zawsze blisko. Wierzy, że to przebywanie z Bogiem (bycie w Bożym świecie) nigdy się nie skończy. Nie wie, co się zdarzy, ale trzyma się Bożego Słowa - obietnicy, że Bóg będzie zawsze nieskończenie blisko. Św. Augustyn w „Wyznaniach" napisał: „Późno Cię ukochałem Piękności dawna i zawsze nowa! (...) Byłeś ze mną, lecz ja nie byłem z Tobą, Panie!". W języku łacińskim brzmi to: <i>Deus</i> <i>interior</i> <i>intimo</i> <i>meo</i>. Można to przełożyć: „Bóg jest bliżej mnie niż ja sam siebie...". To nadzwyczajne, że Bóg jest zawsze i na zawsze z nami! Podczas gdy my odwracamy się od Stwórcy, wyłączamy z Bożego świata, odchodzimy z przestrzeni Życia, Bóg - w swoim Synu Jezusie Chrystusie - nigdy się od nas nie odwraca, nigdy nas nie zostawi(a), nigdy nie przestaje nas kochać. Maryja to słyszy: „<i>Emmanuel...</i> Syn Boży. Bóg, który był i jest, i będzie zawsze ze mną!".<br>
<b>Jesteś błogosławiona!</b> <i>Benedicta</i> oznacza pozdrowiona - obdarzona dobrym Słowem przez Boga. Zatem Bóg Ojciec ma dla Matki swojego Syna najlepsze życzenia. I to Jezus jest źródłem błogosławieństwa dla Maryi. Tytuł <b>błogosławiona</b> odnosi się również do błogosławionego stanu, czyli ciąży. Ponadto w Starym Przymierzu Abram usłyszał od Boga: „Będę ci błogosławił i twoje imię rozsławię: staniesz się błogosławieństwem (...). Przez ciebie będą otrzymywały błogosławieństwo ludy całej ziemi" (Rdz 12,2.3b). To zdanie (proroctwo) w Nowym Przymierzu odnosi się do Najświętszej Maryi Panny! Tam, gdzie pojawi się Maryja, rozlewa się Boże błogosławieństwo! W Ain Karem - w czasie wizyty, którą Miriam złoży Elżbiecie - usłyszy od swojej krewnej: „Błogosławionaś Ty między niewiastami i błogosławiony jest owoc Twojego łona" (Łk 1,42), a w hymnie uwielbienia <i>Magnificat</i> powie (zaśpiewa): „Oto bowiem błogosławić mnie będą odtąd wszystkie pokolenia" (Łk 1,48).<br>
Zatrzymajmy się jeszcze raz przy Słowach, które brzmią w Sercu Miriam z Nazaretu. Zróbmy to nie po to, aby się nauczyć Bożych fraz na pamięć - wszak Pozdrowienie Anielskie jest nam doskonale znane, a modlitwa różańcowa bliska naszym sercom. Ważne jest jednak, żebyśmy przeniknęli do środka Ewangelii, którą Maryja słyszy w czasie Zwiastowania. Ciągle potrzebujemy wchodzić do głębi Bożych Słów, aby odkrywać, że Miriam już w Nazarecie spotyka się ze Słowem Bożym, w którym (i którym) jest Jezus!<br>
<b>Bądź pozdrowiona!</b> Jezus, który jest Pokojem, sprawi, że Maryja zaraz doświadczy wewnętrznego pokoju. Gdy usłyszy: „Duch Święty zstąpi na Ciebie i moc Najwyższego okryje Cię cieniem...!" (Łk 1,35), uchwyci się Bożej obietnicy i przez całe życie będzie żyła w Bożym cieniu - pod miłującym Bożym okiem i pod wszechmocną ręką Pana - w przestrzeni bliskości i potężnej Bożej Łaski. Boży posłaniec doda jeszcze na końcu: „Dla Boga bowiem nie ma nic niemożliwego!" (Łk 1,37). Mam duchową intuicję, że to zdanie będzie brzmiało w sercu Miriam z Nazaretu przez całe życie. Będzie przedmiotem codziennej medytacji, motywem przewodnim wszystkich decyzji, Bożą muzyką na każdy dzień życia. To zdanie przypomni sobie również na Kalwarii, gdy będzie stała w cieniu Ukrzyżowanego i patrzyła, jak Jezus umiera...<br>
<b>Pełna Łaski!</b> Doświadczenie bliskiego kontaktu z Jezusem będzie dla Maryi źródłem pełni życia i największym skarbem i szczęściem...<br>
<b>Pan z Tobą!</b> Choć Jezus opuści rodzinny dom w Nazarecie, będzie nadal żył w przyjaźni i bliskości ze swoją Matką. A zatem nie zostawi Maryi.<br>
<b>Jesteś błogosławiona!</b> Słowa błogosławieństwa Jezusa będą wyznaczały drogę życia Maryi i staną się podstawą wstawiennictwa Maryi - pomocy świadczonej Kościołowi, który od początku widzi w Matce Jezusa nie tylko cudowny przykład życia doskonale zjednoczonego z Bogiem, ale i wspaniałą orędowniczkę u Pana.<br>
Maryja odpowiada: „TAK!". Nie ociąga się. Wierzy, że zamysł Pana jest najlepszą perspektywą. Wyznaje, że pójdzie Bożą drogą. Oddaje się Stwórcy. Słyszymy: „Oto ja służebnica Pańska. Niech mi się stanie według Twojego Słowa!"
<b> </b><br>(Łk 1,38). Ciekawe, że w greckim oryginale nie ma zaimka „ja"(!). Słówko <i>doule</i>, które tłumaczone jest jako „służebnica", może też oznaczać „niewolnica". Zatem ostatnie zdanie Maryi powiedziane do Anioła może brzmieć: „Oto niewolnica Pana! Oby mi się stało (zdarzyło) tak, jak chce Bóg!". Mówi to z wielką pokorą, ale i nadzwyczaj mocno. Ja słyszę tu wielki entuzjazm! Wsłuchajmy się w radosne „TAK!" Maryi. Poprośmy Matkę Pana o odwagę przyjmowania Bożych Słów i o dar całkowitego zaufania i oddania się Bogu!<br>
W czasie Zwiastowania zaczyna się misterium Wcielenia. Młoda mężatka z Nazaretu słyszy Słowo Bożei jest posłuszna Stwórcy. Mocą Ducha Świętego Słowo Boże staje się Ciałem i zaczyna mieszkać wśród nas (zob. J 1,14). Bóg jest w każdym Słowie.<br>
<b>Lektura duchowa</b>
„Doskonałe nabożeństwo do Najświętszej Maryi Panny znamionuje kilka praktyk wewnętrznych. Oto najważniejsze z nich, w skrócie:
- czcić Maryję jako godną Matkę Boga (...) i szanować ponad wszystkich innych świętych jako Arcydzieło łaski i pierwszą po Jezusie Chrystusie, prawdziwym Bogu i prawdziwym człowieku;
- rozważać Jej cnoty, przywileje i czyny;
- rozmyślać o Jej godności i wielkości;
- składać Jej akty miłości, uwielbienia i wdzięczności;
- wzywać Ją serdecznie;
- ofiarowywać się Jej i jednoczyć się z Nią;
- spełniać swe czynności w intencji przypodobania się Jej;
- wszelkie czynności rozpoczynać, wykonywać i kończyć przez Nią, w Niej, z Nią i dla Niej, aby je spełniać przez Jezusa, w Jezusie, z Jezusem i dla Jezusa Chrystusa, naszego ostatecznego celu".
św. Ludwik Maria Grignion de Montfort, <i>Traktat o prawdziwym nabożeństwie do Najświętszej Maryi Panny</i>, 115<br>
<b>Zadanie</b>
Przeczytam z uwagą opis zwiastowania i zastanowię się, jak ja odpowiadam na Boże Słowo.<br>`;

static trescDzien2: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Jezusa Chrystusa, spotkania się z Nim w tajemnicy Bożego Narodzenia i odkrycia, że Jezus przyszedł na świat jako maleńkie Dziecię oraz pozostał z nami w tajemnicy Eucharystii.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„W owym czasie wyszło rozporządzenie cezara Augusta, żeby przeprowadzić spis ludności w całym świecie. Pierwszy ten spis odbył się wówczas, gdy wielkorządcą Syrii był Kwiryniusz. Podążali się więc wszyscy, aby się dać zapisać, każdy do swego miasta. Udał się także Józef z Galilei, z miasta Nazaret, do Judei, do miasta Dawidowego, zwanego Betlejem, ponieważ pochodził z domu i rodu Dawida, żeby się dać zapisać z poślubioną sobie Maryją, która była brzemienna. Kiedy tam przebywali, nadszedł dla Maryi czas rozwiązania. Porodziła swego pierworodnego Syna, owinęła Go w pieluszki i położyła w żłobie, gdyż nie było dla nich miejsca w gospodzie"</i> (Łk 2,1-7).<br>
<b>Rozważanie</b>
Udajmy się do Betlejem. Od wyjścia Gabriela z nazaretańskiego domku Miriam mija dziewięć miesięcy. Znajdujemy się w niewielkiej grocie. Widzimy Maryję, Józefa i maleńkiego Jezusa, który dopiero co się urodził. Czytamy, że dla Świętej Rodziny „nie było miejsca w gospodzie" (Łk 2,7). Przypomina się fragment Prologu Janowej Ewangelii: Słowo „przyszło do swojej własności, a swoi Go nie przyjęli" (J 1,11). To zdanie zawsze mnie porusza i zasmuca. Jak to stało, że Bóg przyszedł i nie został przyjęty??? Co więcej, nie mam wątpliwości, że historia nieprzyjęcia Boga-Człowieka powtarza się i dziś. My też nie (roz)poznajemy i nie przyjmujemy Boga, który ciągle przychodzi.<br>
Przybliżmy się do Maryi. Poprośmy, aby wprowadziła nas w doświadczenie przyjścia na świat Jezusa. Zapytajmy Matkę Pana, co czuje? Czy nie jest rozczarowana? Czy przypuszczała, że niemowlę Jezus wyląduje w żłobie? Miriam patrzy na maleństwo. Być może Jezus mieści się w dłoniach Matki. Jest w ramionach Maryi. Przy sercu Miriam. Całowany i pieszczony przez młodą Mamę (w kolędzie <i>Lulajże, Jezuniu</i> otrzymuje piękne imię „Pieścidełko"). Miriam (roz)poznaje Jezusa w małym Dziecięciu...<br>
Angielska kolęda Mary, <i>Did You Know?</i> ma piękny tekst: „Maryjo, czy wiedziałaś, że Twój maleńki Chłopiec pewnego dnia po wodzie będzie kroczył? (...), że (...) ocali naszych synów i nasze córy? (...) że (...) przyszedł, by odmienić Cię? (...) Chwała Barankowi! (...) Czy wiedziałaś, że Twój maleńki Chłopiec jest niebiańskim Barankiem bez skazy? Śpiące Dziecię, które trzymasz, to wielki Jestem, Który Jestem".<br>
Miriam patrzy na Jezusa. I my wpatrujmy się w maleńkiego Boga-Człowieka. Maryja przeżywa czas najgłębszej modlitwy - uwielbienia i wdzięczności, adoracji i trwania w Bożej (Jezusowej) obecności, duchowego skupienia i kontemplacji. Zapytajmy jeszcze raz Maryi, co czuje, gdy widzi Jezusa Noworodka?<br><br>Miriam wie(rzy), że to Syn Boży. Bóg zdany na człowieka. Bóg, który powierza się człowiekowi. Bóg kryje się w bezbronnym, bezradnym i bezsilnym Dziecięciu. Jak uwierzyć, że właśnie tu, w Betlejem - na krańcu świata - rodzi się Bóg, który jest Panem? Jak zobaczyć Boga w maleńkim Człowieku? Noc Bożego Narodzenia pokazuje, ile paradoksów kryje się w tajemnicy przyjścia Syna Bożego na świat. Franciszek Karpiński ujmuje to w znanej kolędzie: <i>Bóg się rodzi</i>. Śpiewamy (i rozmyślamy, jak to możliwe, że...): „Bóg (Ktoś, kto nie ma początku) się rodzi... Moc (niezachwiana) truchleje (zaczyna się chwiać)... Pan niebiosów (ukryty w majestacie Nieba) obnażony... Ogień krzepnie... Blask ciemnieje... Ma granice nieskończony... Wzgardzony okryty chwałą... Śmiertelny Król nad wiekami...". To piękna poezja, dzięki której możemy poczuć, że Boży świat, który nas nieskończenie przewyższa, łączy się z naszą rzeczywistością. W Jezusie Bóg staje się Człowiekiem, aby człowiek stał się jedno z Bogiem. Bóg staje się ludzki, aby człowiek stał się Boży. Ludzki Bóg przychodzi, abyśmy odkryli, że jesteśmy na obraz i podobieństwo Stwórcy (zob. Rdz 1,27) i przez to ukazywali światu, że Bóg nie mieszka w swoich za-światach. Nie przebywa z dala od nas - za naszym światem. Jest wśród nas. Wewnątrz naszego życia. Między nami.<br>
Maryja ciągle wpatruje się w maleńkiego Jezusa. Zapewne myśli o Bożym planie. Być może zastanawia się, co zrobić, żeby Bóg został (roz)poznany przez ludzi. Przychodzą pasterze i mędrcy. Miriam jest pogrążona w modlitwie. Jednak piękny i spokojny czas bycia z maleńkim Bogiem-Człowiekiem wkrótce się skończy. Miną dni i Matka Pana zostanie w nocy obudzona przez Józefa i usłyszy, że muszą niezwłocznie uciekać do Egiptu... Że jest ktoś, kto chce zamordować Dziecko. I znowu zrodzą się w sercu pytania: „Jak to możliwe? Dlaczego tak się dzieje?".<br>
Jesteśmy w Betlejem. Nazwa miasta, w którym 1000 lat przed Jezusem urodził się król Dawid, oznacza dosłownie „Dom Chleba". Tak misterium przyjścia Boga-Człowieka na świat łączy się z misterium Eucharystii, a tajemnica Bożego Narodzenia jest przejawem (dowodem) nieskończonej Miłości Boga do człowieka. Bóg w cudowny sposób się materializuje - wpisuje swoją obecność w widzialny świat. Przez 33 lata Jezus będzie fizycznie przemierzał Ziemię Świętą wzdłuż i wszerz. W Wielki Piątek umrze, ale w nocy z Wielkiej Soboty na Wielką Niedzielę powstanie z martwych, a po 40 dniach wstąpi do Nieba. I właśnie wtedy apostołowie doświadczą prawdy Jezusowych słów: „A oto Ja jestem z wami przez wszystkie dni, aż do skończenia świata" (Mt 28,20). Pan obiecuje, że nie pozostawi swoich. W Wielki Czwartek ustanowi Najświętszy z sakramentów. Apostołowie usłyszą: „Bierzcie i jedzcie, to jest Ciało moje..." (Mt 26,26) i przyjmą Boży Chleb - Eucharystię. Jezus doda też: „Czyńcie to na moją pamiątkę!" (1 Kor 11,24). Odtąd obecność Boga w Człowieku zostanie przedłużona - Pan stanie się obecny w świecie również w kawałkach Chleba i kroplach Wina. Jest z nami widzialnie przez wszystkie dni...<br>
Jezus rodzi się w Betlejem - Domu Chleba, aby zapowiedzieć, że będą wznoszone nowe domy Chleba - kościoły, gdzie będzie sprawowana Najświętsza Ofiara. A zatem każda świątynia jest (jak) Betlejem.<br>
Maryja milczy. Jest zanurzona w ciszy. Ewangeliści nie wspominają choćby jednego słowa, które by Maryja wypowiedziała przy Bożym Narodzeniu. Bo wobec tajemnicy przyjścia (przychodzenia) Boga na świat najlepszą postawą jest kontemplacja. Intensywne wpatrywanie się w pokornego Boga, który na początku swojej widzialnej obecności w świecie objawia się w maleńkim Człowieku, a dziś kryje się w kruchym Chlebie, stoi u źródeł Bożego doświadczenia - spotkania z Panem. Tak rodzi się modlitwa, która w najgłębszym wymiarze jest trwaniem przed Jezusem i spotkaniem twarzą w twarz. Tak rodzi się intymna wspólnota z Bogiem-Chlebem, który przez Komunię Świętą żyje i mieszka z nami i dzieli to, co nasze. Wejdźmy w to milczenie Maryi. Poprośmy Matkę pięknej Miłości, by nauczyła nas w ciszy wpatrywać się w Jezusa.<br>
Nasze życie czerpie najlepszą naukę o Bogu z Betlejem, a Maryja jest tu wspaniałą Nauczycielką. Uczy nas wierzyć, że w maleńkim Dziecięciu Bóg wybiera to, co małe, zwyczajne, proste. Budzi w nas nadzieję, że w Jezusie-Niemowlęciu Bóg jest Królem i rzeczywiście panuje. I wreszcie pokazuje, że spojrzenie miłości sięga głębi bytu i przenika to, co widzialne. Miłość rozpoznaje Boga w maleńkim Dziecku i zachwyca się małym-wielkim Bogiem-Człowiekiem...<br>
Jesteśmy blisko Maryi, która w Betlejem - Domu Chleba poznaje Jezusa. Matka Pana chce nam powiedzieć, że ze spotkania z Jezusem-Dzieckiem oraz z Jezusem-Chlebem, rodzi się pragnienie dawania miłości ludziom - naszym siostrom i braciom. Pan przypomina: „Wszystko, co uczyniliście jednemu z tych braci moich najmniejszych, Mnieście uczynili" (Mt 25,40). Jezus jest Dzieckiem w każdym człowieku! Każdy napotkany człowiek „przynosi" nam Jezusa. Dlatego też przyjmując Komunię Świętą przyjmujemy nie tylko Jezusa, ale też otwieramy drzwi serca dla wszystkich bliźnich, z którymi krzyżują się nasze drogi. Słowo <i>Amen</i>, które jest na ustach każdego przyjmującego Komunię Świętą, to zatem nie tylko akt wiary w Jezusa ukrytego w kawałku Chleba (wszak karmimy się Ciałem Chrystusa), ale także wyznanie naszej przynależności do wspólnoty Kościoła (mistycznego Ciała Chrystusa). Przebywając w Betlejem, prośmy Matkę Zbawiciela, aby uczyła nas rozpoznawać Syna Bożego w każdym człowieku.<br>
Jezus woła nas: „Pójdźcie, błogosławieni u Ojca mojego, weźcie w posiadanie królestwo, przygotowane dla was od założenia świata! Bo byłem głodny, a daliście Mi jeść; byłem spragniony, a daliście Mi pić; byłem przybyszem, a przyjęliście Mnie; byłem nagi, a przyodzialiście Mnie; byłem chory, a odwiedziliście Mnie; byłem w więzieniu, a przyszliście do Mnie" (Mt 25,34-36).<br>
Jezus woła do nas: „Kto spożywa moje Ciało i pije moją Krew, ma życie wieczne, a Ja go wskrzeszę w dniu ostatecznym. Ciało moje jest prawdziwym pokarmem, a Krew moja jest prawdziwym napojem. Kto spożywa moje Ciało i Krew moją pije, trwa we Mnie, a Ja w nim. Jak Mnie posłał żyjący Ojciec, a Ja żyję przez Ojca, tak i ten, kto Mnie spożywa, będzie żył przeze Mnie" (J 6,54-57).<br>
<b>Lektura duchowa</b>
<i>„Bóg Duch Święty, w Bogu niepłodny, to znaczy - nie dający początku innej Osobie Boskiej, stał się płodny przez Maryję, którą poślubił. Z Nią i w Niej, i przez Nią ukształtował swe Arcydzieło - Boga Wcielonego i aż do końca świata codziennie kształtuje wybranych i członki Mistycznego Ciała Chrystusa. Toteż, im bardziej odkrywa On Maryję, swą umiłowaną i nierozłączną Oblubienicę, w jakiejś duszy, tym silniej i skuteczniej działa na nią, by ukształtować w owej duszy Jezusa Chrystusa, a duszę w Jezusie Chrystusie. Nie znaczy to, jakobym chciał rzec, że Najświętsza Maryja Panna dawała Duchowi Świętemu płodność, której On nie posiadał. Będąc Bogiem, posiada On płodność tak samo, jak Ojciec i Syn, choć nie wprowadza jej w czyn, ponieważ nie daje początku żadnej innej Osobie Boskiej. Pragnę jednak powiedzieć, że Duch Święty, który Najświętszej Panny nie potrzebuje koniecznie, chciał jednak użyć Jej pośrednictwa dla okazania swojej płodności, kształtując w Niej i przez Nią Jezusa Chrystusa oraz Jego członki. Oto tajemnica łaski, ukryta nawet przed największymi uczonymi i najbardziej uduchowionymi spośród chrześcijan. Sposób postępowania, jaki przyjęły trzy Osoby Trójcy Przenajświętszej przy Wcieleniu i przy pierwszym przyjściu na świat Jezusa Chrystusa, jest niezmienny. Codziennie zachowują One w sposób niewidzialny to samo postępowanie w Kościele świętym i będzie tak do końca świata, do ostatniego przyjścia Jezusa Chrystusa".</i>
św. Ludwik Maria Grignion de Montfort, <i>Traktat o prawdziwym nabożeństwie do Najświętszej Maryi Panny</i>, 20-22<br>
<b>Zadanie</b>
W najbliższym czasie pójdę dodatkowo na adorację Najświętszego Sakramentu, aby uczcić Ciało Chrystusa żyjącego w Eucharystii.<br>`;

static trescDzien3: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Jezusa Chrystusa, spotkania się z Nim w tajemnicy Ofiarowania w jerozolimskiej świątyni i odkrycia, że Pan prowadzi nas po drogach codzienności, ucząc wierności Prawu Bożemu.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„Gdy potem upłynęły dni ich oczyszczenia według Prawa Mojżeszowego, przynieśli Je do Jerozolimy, aby przedstawić Panu. Tak bowiem jest napisane w Prawie Pańskim: Każde pierworodne dziecko płci męskiej będzie poświęcone Panu. Mieli również złożyć w ofierze parę synogarlic albo dwa młode gołębie, zgodnie z przepisem Prawa Pańskiego (...). A Jego ojciec i Matka dziwili się temu, co o Nim mówiono. Symeon zaś błogosławił Ich i rzekł do Maryi, Matki Jego: «Oto Ten przeznaczony jest na upadek i na powstanie wielu w Izraelu, i na znak, któremu sprzeciwiać się będą - a Twoją duszę miecz przeniknie - aby na jaw wyszły zamysły serc wielu». A gdy wypełnili wszystko według Prawa Pańskiego, wrócili do Galilei, do swego miasta - Nazaretu. Dziecię zaś rosło i nabierało mocy, napełniając się mądrością, a łaska Boża spoczywała na Nim"</i> (Łk 2,22-24, 33-35, 39-40).<br>
<b>Rozważanie</b>
Przychodzimy wraz ze Świętą Rodziną do Jerozolimy. Od narodzin Jezusa mija 40 dni. Maryja i Józef wnoszą maleńkiego Pana do świątyni. Postępują tak, aby się spełniło to, co jest napisane w Prawie Pańskim: Każde pierworodne dziecko płci męskiej będzie poświęcone Panu. Maryja i Józef są przejęci. Nie mają wątpliwości (jak wszyscy pobożni członkowie narodu izraelskiego), że Jerozolima to Święte Miasto - miejsce wybrane przez Boga, a świątynia wzniesiona przez Heroda to nie tylko arcydzieło architektury i chluba wszystkich Żydów, ale to przede wszystkim Dom, w którym mieszka Bóg Jahwe. Towarzyszmy Świętej Rodzinie. Zobaczmy radość, szczęście i dumę, które malują się na twarzach Maryi i Józefa. Mają głęboką świadomość, że świątynia to uprzywilejowane miejsce, w którym mogą spotkać się z Bogiem i pomodlić.<br>
Maryja i Józef to prawdziwi Izraelici. Są wierni Prawu Bożemu. Patrząc na to, co dzieje się w świątyni jerozolimskiej podczas Ofiarowania Jezusa, jesteśmy świadkami wiernego wypełniania przez Świętą Rodzinę przykazań Tory. Zdumiewa mnie wierność Maryi i Józefa wobec Prawa Starego Testamentu. Szacunek wobec przepisów płynął z przeświadczenia, że to Prawo jest Bożym (Słowem), a to, co Bóg proponuje, wyznacza dla nas drogę najlepszych decyzji i wyborów. I choć Żydzi przesadzili z ilością norm (613 <i>micwot</i> - przykazań - kanonów prawnych: 365 zakazów i 248 nakazów), to jednak tradycje i zwyczaje co do najważniejszych świąt oraz przepisy regulujące kwestię czystości rytualnej były tak dla Maryi i Józefa, jak i Jezusa, ważne. Z punktu widzenia przepisów rytualnych Maryja po urodzeniu Jezusa była nieczysta. Właśnie dlatego przychodzi do świątyni jerozolimskiej, aby złożyć ofiarę za swoje oczyszczenie. Ponadto chce powierzyć Bogu - Ojcu Syna - Jezusa. Maryja i Józef kładą Jezusa przed Jahwe. Przedstawiają Dziecko Ojcu. Powierzają czterdziestodniowe Niemowlę Bogu. Maryja czyni to z wielkim wzruszeniem. Chce powiedzieć do Boga: „Jezus nie jest moją własnością. Jest Synem moim, ale przede wszystkim Twoim!".<br>
Wczujmy się w klimat świętego miejsca. Bądźmy blisko Maryi i Józefa. Zobaczmy, co robią? Co czują, kładąc Jezusa przed obliczem Boga i czyniąc przez to zadość Bożemu Prawu? Najpierw widzą Jezusa - Syna-Człowieka, a w Jezusie Miłość. Pierwsze jest zawsze doświadczenie osobistego spotkania z Bogiem. Dopiero na drugim miejscu szacunek i wierność wobec Prawa. Pierwsza jest miłość! Dopiero na drugim miejscu wierność miłości. A zatem chrześcijaństwo nie jest tylko drogą tradycji i religijnych zwyczajów. Jest spotkaniem z żywym Bogiem. Ciągle mam w pamięci to, co napisał kiedyś Benedykt XVI: „U początku bycia chrześcijaninem nie ma decyzji etycznej czy jakiejś wielkiej idei, ale jest natomiast spotkanie z wydarzeniem, z Osobą, która nadaje życiu nową perspektywę, a tym samym decydujące ukierunkowanie" (<i>Deus Caritas est</i>, 1). To nie Prawo nas ocala, ale Jezus, który przychodzi, aby dopełnić i udoskonalić Prawo Starego Przymierza. I jako duchowy Nauczyciel posyła Ducha Świętego, którego działanie sprawia, że każdy przepis prawny nie stanowi ograniczenia wolności, lecz pokazuje właściwy kierunek życia. Duch Święty, który mieszka w sercach Bożych ludzi, owocuje wspaniałymi cnotami. Św. Paweł pisze: „Owocem zaś ducha jest: miłość, radość, pokój, cierpliwość, uprzejmość, dobroć, wierność, łagodność, opanowanie. Przeciw takim [cnotom] nie ma Prawa (...). Mając życie od Ducha, do Ducha się też stosujmy" (Ga 5,22-23.25). Jakie to ważne i odważne nauczanie. Otrzymaliśmy Ducha Świętego, który nas uczy żyć i przypomina to wszystko, co głosił Jezus.<br>
W scenie Ofiarowania widzimy Jezusa jako wiernego Prawu Miłości. W kwestii rozumienia Prawa ogromnie ważne jest odkrycie wewnętrznej strony (ducha) Prawa. Litera jest zawsze zewnętrzną stroną wewnętrznej rzeczywistości. W Ewangeliach czytamy, że Pan uzdrawiał w szabat, choć to było zabronione, bo wiedział, że dobro człowieka jest wielką wartością i stanowi ducha Prawa, a sama wierność literze nie wystarczy. Dla Pana Prawo nie jest celem samym w sobie, ale zostało dane dla dobra człowieka. Wściekli faryzeusze troszczący się o wierność każdemu „drobiazgowi" Tory usłyszeli wtedy: „Albowiem Syn Człowieczy jest Panem szabatu" (Mt 12,8).<br>
Patrzmy na Maryję i uczmy się posłuszeństwa Prawu - ufności wobec Bożych rozporządzeń. Dziś to zaufanie wobec Boga, który przez Kościół prowadzi swój Lud do Nieba, zdaje się być niełatwym wyborem. Żyjemy w czasach kryzysu autorytetów i kwestionowania instytucji, które przez tysiące lat cieszyły się uznaniem. Odnosi się to niestety do Kościoła Katolickiego jako wspólnoty wiernych, której fundamentem jest papiestwo. Dziś coraz częściej ludzie, którzy deklarują swoją przynależność do Kościoła Katolickiego, dystansują się od nauczania papieskiego, kwestionują przepisy prawne wprowadzone przez widzialnych Pasterzy Bożej Owczarni. Wielka pokusa, jaką jest odrzucenie Prawa (i nauczania) Kościoła oraz szukanie własnej drogi do prawdy i pełni życia (Nieba), dotyczy zatem nie tylko ludzi, którzy tracą wiarę i żyją na rubieżach Kościoła. Zaufanie do Prawa formułowanego przez Kościół i posłuszeństwo wobec Bożego głosu wyrażonego w oficjalnym nauczaniu Ojca Świętego są dziś bardzo potrzebne. Patrząc na Maryję, która widzi w Jezusie nie tylko Człowieka pokornie przyjmującego ludzką kondycję życia, ale także żydowskie Dziecko podległe Prawu, uczymy się od Miriam szacunku wobec autorytetu władzy duchowej i zaufania wobec rozporządzeń i norm Bożego Kościoła. Maryja nie ma wątpliwości, że wierność Bożemu Prawu jest wartością i pozwala dobrze żyć i kierować się ku Niebu.<br>
Na scenie w czasie Ofiarowania pojawia się także niemłody człowiek. Ma na imię Symeon. Starzec prorokuje, że kiedyś Miriam będzie bardzo cierpiała: „A Twoją duszę miecz przeniknie - aby na jaw wyszły zamysły serc wielu" (Łk 2,35). Maryja jest zaskoczona i przejęta. Nie wie, co się zdarzy, ale proroctwo Symeona pozostanie jako pewnego rodzaju cie(r)ń. Zapowiedź przebicia Serca mieczem spełni się, gdy Pan będzie umierał na krzyżu. Maryja pójdzie drogą Miłości i pozostanie wierna Jezusowi aż po śmierć. Nie umrze śmiercią męczeńską, ale będzie współcierpiała z Jezusem. Spotkanie z Miłością rodzi pragnienie wierności. Miłość do Jezusa zaowocuje wejściem na drogę wierności Prawu (Miłości). Poprośmy Maryję, aby dała nam dostęp do swojego niepokalanego Serca...<br>
Zakończeniem ewangelicznej opowieści o wierności świętej Rodziny wobec Bożego Prawa (...wypełnili wszystko według Prawa Pańskiego) jest krótkie zdanie przedstawiające drogę rozwoju Jezusa, który jak każde dziecko będzie rósł i nabywał wszelkich umiejętności. Jakie to piękne, że Jezus i tu jest do nas podobny. Że nie przyszedł na świat „gotowy". Bóg uwzględnia prawo procesu - stopniowego rozwoju. Dlatego powiedział: „Bądźcie świętymi, bo Ja jestem święty, Pan, Bóg wasz!" (Kpł 19,2). W wymiarze życia doczesnego doskonałość nie jest stanem, który możemy osiągnąć tu - na ziemi raz na zawsze. I nie jest tylko owocem wierności Prawu Bożemu, ale też (i przede wszystkim) darem Bożej Miłości. To ciągły trud wymagający walki z samym sobą, ale też otwierający na cuda Bożej interwencji i pomocy. Prośmy Maryję, aby przypominała nam istotę Bożego Prawa - cudowną Bożą propozycję: „Stawajcie się świętymi!". Módlmy się, abyśmy ciągle wchodzili na drogę świętości, która nie jest bezgrzesznością, a ciągłym nawracaniem się - zawracaniem ze złej drogi i zwracaniem się do Stwórcy z miłością.<br>
Jezus zaprasza: „Przyjdźcie do Mnie wszyscy, którzy utrudzeni i obciążeni jesteście, a Ja was pokrzepię. Weźcie moje jarzmo na siebie i uczcie się ode Mnie, bo jestem cichy i pokorny sercem, a znajdziecie ukojenie dla dusz waszych. Albowiem jarzmo moje jest słodkie, a moje brzemię lekkie" (Mt 11,28-30). Rabini uczyli, że jarzmem ziemskim jest dla człowieka wierność Prawu Bożemu. Ale przypominali też o jarzmie niebiańskim - ufności w Bożą miłość, która przybliża do Nieba i otwiera nam Raj.<br>
<i>Veni, Sancte Spiritus! Veni, Sancte Spiritus! Veni, Sancte Spiritus!</i><br>
<b>Lektura duchowa</b>
<i>„O, Duchu Święty! Udziel mi wszystkich łask oraz zasadź, zraszaj i uprawiaj w mojej duszy umiłowaną Maryję, Drzewo prawdziwego Życia, aby ono rosło, kwitło i przynosiło obfity owoc życia. Duchu Święty! Daj mi wielkie nabożeństwo i obdarz mnie wielką miłością do Twojej Najświętszej Oblubienicy; daj, bym - bym zawsze w oparciu o Jej matczyne łono - i nieustannie uciekał się do Jej miłosierdzia, tak, abyś to w Niej kształtował we mnie Jezusa Chrystusa, wielkiego i potężnego, aż do pełni Jego doskonałego wieku. Amen!"</i>
św.<i> </i>Ludwik Maria Grignion de Montfort, <i>Tajemnica Maryi, </i>67<br>
<b>Zadanie</b>
Zwrócę się w modlitwie do Ducha Świętego, aby pokazał mi drogę wierności i posłuszeństwa Bożemu Prawu miłości.<br>`;

static trescDzien4: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Pana Jezusa, spotkania z Nim w tajemnicy Znalezienia w świątyni i odkrycia, że Pan przychodzi do nas w najcięższych chwilach naszego życia i chce byśmy Go szukali i znaleźli. On nadaje sens najtrudniejszym doświadczeniom naszej codzienności.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„Rodzice Jego chodzili co roku do Jerozolimy na Święto Paschy. Gdy miał lat dwanaście, udali się tam zwyczajem świątecznym. Kiedy wracali po skończonych uroczystościach, został młody Jezus w Jerozolimie, a tego nie zauważyli Jego Rodzice. Przypuszczając, że jest wśród pątników, uszli dzień drogi i szukali Go między krewnych i znajomych. Gdy Go nie znaleźli, wrócili do Jeruzalem szukając Go. Dopiero po trzech dniach odnaleźli Go w świątyni, gdzie siedział między nauczycielami, przysłuchiwał się im i zadawał pytania. Wszyscy zaś, którzy Go słuchali, byli zdumieni bystrością Jego umysłu i odpowiedziami. Na ten widok zdziwili się bardzo, a Jego Matka rzekła do Niego: «Synu, czemuś nam to uczynił? Oto ojciec Twój i ja z bólem serca szukaliśmy Ciebie». Lecz On im odpowiedział: «Czemuście Mnie szukali? Czy nie wiedzieliście, że powinienem być w tym, co należy do mego Ojca?» Oni jednak nie zrozumieli tego, co im powiedział"</i> (Łk 2,41-50).<br>
<b>Rozważanie</b>
Jesteśmy znowu w Świętym Mieście Żydów - Jerozolimie. Mija 12 lat od narodzin Zbawiciela. Jest uroczysty czas Paschy. Święta Rodzina przybywa na Święto do Jerozolimy, aby we wspólnocie wiary uroczyście przeżyć pamiątkę Exodusu - Wyjścia Narodu Wybranego z Egiptu. Wspomniałem o Świętej Rodzinie, ale na początku ewangelicznego zdarzenia widzimy tylko Maryję i Józefa. Są sami. Szukają Jezusa. Okazuje się, że nawet Najświętsza Maryja Panna i święty Józef mogą zgubić Jezusa. Opis szukania i znalezienia Pana w świątyni pokazuje, że i w Świętej Rodzinie mógł zdarzyć się mały „kryzys". Po Święcie Paschy Jezus został w Jerozolimie i dopiero po trzech dniach został odnaleziony. Fascynujące jest to szukanie dwunastoletniego Pana przez Maryję i Józefa. Święty Łukasz pisze, że odnaleźli Go po trzech dniach. Maryja i Józef szukają Jezusa z wielką determinacją. Szukają, żeby znaleźć. Szukają, aż znajdą. I znajdują! Możemy się uczyć od Maryi i Józefa postawy cierpliwego i wytrwałego szukania Jezusa. Wejdźmy do wnętrza Maryi szukającej Pana? Co czuje Matka Jezusa? Denerwuje się? Boi się, że dwunastoletniemu Jezusowi może stać się krzywda? Czuje niepewność? Na pewno wraz z Józefem gorliwie szuka Syna.<br>
Wysiłek Świętej Rodziny zostaje wynagrodzony. Jezus znajduje się (zostaje znaleziony) w świątyni jerozolimskiej. I tu zadziwia reakcja dwunastolatka na wyrzut Maryi: „Synu, czemuś nam to uczynił?" (Łk 2,48) Pan na pytanie odpowiada pytaniem: „Czemuście Mnie szukali?" ?" (Łk 2,49) I dodaje: „czy nie wiedzieliście, że powinienem być w tym , co należy do mego Ojca?" ?" (Łk 2,49) Kapitalny dialog, dzięki któremu poznajemy Jezusa. Wiemy, że Syn chce być z Ojcem.<br>
Miną lata, a Zbawiciel rozraduje się w Duchu Świętym i zawoła: „Wysławiam Cię, Ojcze, Panie nieba i ziemi, że zakryłeś te rzeczy przed mądrymi i roztropnymi, a objawiłeś je prostaczkom. Tak, Ojcze, gdyż takie było Twoje upodobanie. Wszystko przekazał Mi Ojciec mój. Nikt też nie zna Syna, tylko Ojciec, ani Ojca nikt nie zna, tylko Syn, i ten, komu Syn zechce objawić. Przyjdźcie do Mnie, wszyscy..." (Mt 11,25-28). Możemy rozważać cudowne Słowa, w których Jezus-Syn przyznaje się do Boga-Ojca i zapowiada, że objawi nam najgłębszą prawdę o Stwórcy. W modlitwie Zbawiciela Stwórca najpierw jest Ojcem, a dopiero później Panem całego wszechświata. W czwartej Ewangelii Pan zapewnia nas także: „Już was nie nazywam sługami, bo sługa nie wie, co czyni jego pan, ale nazwałem was przyjaciółmi, albowiem oznajmiłem wam wszystko, co usłyszałem od Ojca mego" (J 15,15). To kapitalne Słowa - swoistego rodzaju zwieńczenie całego objawienia, które przynosi światu Jezus. Syn Boży powiedział nam o Ojcu-Bogu wszystko! Wszystko!!! Niczego przed nami nie ukrył! Oczywiście pełnia poznania Boga dokona się w Niebie - św. Paweł pisze: „lecz właśnie [nauczamy], jak zostało napisane: Ani oko nie widziało, ani ucho nie słyszało, ani serce człowieka nie zdołało pojąć, jak wielkie rzeczy przygotował Bóg tym, którzy Go miłują" (1 Kor 2,9), ale Jezus zostawia nam na ziemi przedsmak pełni.<br>
Wróćmy do jerozolimskiej świątyni. Niech w naszych sercach zapisze się pytanie, które Maryja stawia Jezusowi: „DLACZEGO?" My też mamy prawo tak pytać. Jeżeli w naszym życiu docieramy do rzeczywistości, których nie rozumiemy, zawsze i o wszystko możemy pytać Boga. Tak, jak Maryja. Miriam pyta i szuka głębi. My też możemy zejść na głębszy poziom i zadać pytanie nie tyle dlaczego dzieją się trudne rzeczy w naszym życiu, co zapytać, kto jest Panem Nieba i ziemi? Kto jest naszym Bogiem? Najlepsza modlitwa nie wyklucza walki wewnętrznej, zmagania o to, aby trwać przy Bogu i nie zwątpić - nie odejść od Pana. Na samym końcu możemy jednak wyznać: „Jezu! Ty jesteś naszym Panem! Wierzymy, że dla Ciebie wszystko, co przeżywamy, ma sens!". Zatem to, co istotne i kluczowe w tekście o znalezieniu Jezusa w świątyni, odnosi się do szukania - pytania o sens. Maryja zdaje się nam mówić, że wszystkie pytania, które nas nurtują i dręczą (na które nie ma odpowiedzi), najlepiej wpisać w modlitwę. Tylko to, co „przerabiamy" na modlitwie, ma szansę doczekać się Bożej odpowiedzi i działania. Spoglądajmy na Jezusa. Dwunastoletni Pan modli się w świątyni. Nie tylko rozmawia ze starszyzną Izraela. Jest w przestrzeni Ojca. To Człowiek zatopiony w Bogu - przebywający wewnątrz Bożego świata. Syn z Ojcem i w Ojcu. Minie 20 lat i apostołowie usłyszą od Pana: „Ja nie jestem sam, bo Ojciec jest ze Mną" (J 16,32). To wspaniałe Słowa wyrażające doskonałą więź łączącą Ojca z Synem - Miłość, która jest treścią Życia Trójcy Przenajświętszej. To właśnie Miłość sprawia, że Jezus - Syn Boży i Syn Człowieczy - zamiast spać w nocy i odpoczywać - modli się. Rozmawia z Ojcem - Bogiem. Tworzy z Ojcem relację MIŁOŚCI. Ciągle ma czas, bo kocha. Prośmy Jezusa, aby wprowadził nas w to doświadczenie MIŁOŚCI, która jest w Bogu.<br>
Patrzmy na Maryję. Słyszy odpowiedź Jezusa. Nie wszystko rozumie. Ale pieczołowicie gromadzi w swoim Sercu wszystkie Jego Słowa. Poprośmy Maryję, aby wprowadziła nas w swoje doświadczenie szukania i znalezienia Jezusa w świątyni jerozolimskiej oraz aby pomagała nam szukać Bożego sensu we wszystkich nawet najbardziej dramatycznych ludzkich wydarzeniach.<br>
<b>Lektura duchowa</b>
<i>„Postanówcie, drodzy Przyjaciele Krzyża, wszystkie rodzaje krzyży znosić bez wyjątku i bez wyboru: wszelkie ubóstwo, wszelką niesprawiedliwość, utratę, chorobę, upokorzenie, przeciwności, oszczerstwo, oschłość; każde opuszczenie, wszelką wewnętrzną i zewnętrzną udrękę - zawsze mówiąc: Serce moje jest gotowe, Boże (Ps 108,2). Bądźcie więc gotowi na to, że będziecie opuszczeni przez ludzi i aniołów, i jakby przez samego Boga; że będziecie prześladowani, otaczani zazdrością, zdradzani, oczerniani i spotwarzani przez wszystkich; że będziecie cierpieć głód, pragnienie, żebranie, nagość, wygnanie, więzienie, szubienicę i wszystkie tortury, chociaż nie zasłużyliście na nie zarzucanymi wam zbrodniami".</i>
św.<i> </i>Ludwik Maria Grignion de Montfort, <i>List okólny do Przyjaciół Krzyża</i>, 54<br>
<b>Zadanie</b>
Wszystkie trudne sytuacje, których doświadczam, oddam Panu Bogu na modlitwie. Zdobędę się na odwagę aby, zapytać: „Panie dlaczego?", ale dodam: „Bądź wola Twoja".<br>`;

static trescDzien5: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Pana Jezusa, spotkania z Nim w tajemnicy Cudu dokonanego w Kanie Galilejskiej i odkrycia, że Pan zawsze działa, ilekroć poprosimy o Bożą interwencję.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„Trzeciego dnia odbywało się wesele w Kanie Galilejskiej i była tam Matka Jezusa. Zaproszono na to wesele także Jezusa i Jego uczniów. A kiedy zabrakło wina, Matka Jezusa rzekła do Niego: «Nie mają wina». Jezus Jej odpowiedział: «Czyż to moja lub Twoja sprawa, Niewiasto? [Czyż] jeszcze nie nadeszła godzina moja?» Wtedy Matka Jego powiedziała do sług: «Zróbcie wszystko, cokolwiek wam powie». Stało zaś tam sześć stągwi kamiennych przeznaczonych do żydowskich oczyszczeń, z których każda mogła pomieścić dwie lub trzy miary. Jezus rzekł do sług: «Napełnijcie stągwie wodą!» I napełnili je aż po brzegi. Potem powiedział do nich: «Zaczerpnijcie teraz i zanieście staroście weselnemu». Ci więc zanieśli. Gdy zaś starosta weselny skosztował wody, która stała się winem - a nie wiedział, skąd ono pochodzi, ale słudzy, którzy czerpali wodę, wiedzieli - przywołał pana młodego i powiedział do niego: «Każdy człowiek stawia najpierw dobre wino, a gdy się napiją, wówczas gorsze. Ty zachowałeś dobre wino aż do tej pory». Taki to początek znaków uczynił Jezus w Kanie Galilejskiej. Objawił swoją chwałę i uwierzyli w Niego Jego uczniowie"</i> (J 2,1-11).<br>
<b>Rozważanie</b>
Zobaczę Jezusa bliskiego człowiekowi. Będę patrzył, jak uczestniczy w weselu.
Cieszę się, że w Ewangelii są opisy pokazujące, że Jezus nie żył tylko w swoim „Bożym świecie". Jest w samym środku życia człowieka („A słowo stało się ciałem i zamieszkało wśród nas" (J 1,14) - w wersji oryginalnej: „Słowo (...) rozbiło namiot w nas"). Pan uczestniczy w radościach (weselach), ale i w smutkach (pogrzebach). Jest z nami na dobre i złe. A w ludzkim życiu często to, co piękne i poruszające, przeplata się z bolesnym i budzącym niepokój. W Kanie Galilejskiej Jezus bierze udział w radości nowożeńców. Tyle że już na początku wspólnego życia młodym małżonkom brakuje wina, czyli miłości.<br>
Na szczęście w Kanie Galilejskiej jest Maryja, która delikatnie pokazuje Jezusowi problem młodej pary. Pan odpowiada niezbyt miło, jakby nie uwzględniał punktu widzenia Matki. Ale Maryja w zdaniu: „Czyż to moja lub Twoja sprawa, Niewiasto? Czyż nie nadeszła godzina moja?" słyszy to, czego my (chyba) nie słyszymy. Zawsze mnie dziwi nadzwyczajna rada, jaką Miriam daje sługom: „Zróbcie wszystko, co wam powie" (J 2,5). Maryja pokazuje nam Jezusa, który wszystko może.<br>
Słudzy napełniają wodą wielkie naczynia. Nalanie wody do stągwi to trud, który wkładamy w życie. Stągwie symbolizują nasze serca i to, co dzieje się w życiu. Są kamienne - jak twarde ludzkie serca; zagrzebane w ziemi - ujawniają stan życia wszystkich, którzy choć ciągle chodzą po ziemi, w wymiarze duchowym już dawno umarli, bo żyją z dala od Boga - jedynego dawcy Życia; nieruchome (nieporuszone) - jak ludzie, którzy są pogrążeni w obojętności wobec Boga oraz w niewrażliwości duchowo-moralnej...<br>
Woda w naczyniach symbolizuje to, co ciężkie (trudne do zniesienia) i twarde (trudne do zrozumienia) w naszym życiu. Sześć ciężkich stągwi może być symbolem sześciu trudnych do udźwignięcia (uniesienia) wymiarów życia.<br>
Po pierwsze to proza (szarość i monotonia) życia.
Po drugie to niepokój przed grożącymi niebezpieczeństwami.
Po trzecie to patrzenie na codzienność z perspektywy obowiązków i powinności (regułą życia jest zasada: działam, bo muszę).
Po czwarte to ludzka kruchość i niemoc.
Po piąte to samotność i niezrozumienie.
Po szóste to przemijanie i perspektywa śmierci.
Co czyni Jezus? Sprawia cud przemiany! Woda staje się winem, które symbolizuje treść i właściwość życia - radość płynącą z przelewającej się miłości. Wino obrazuje też to, co ma wartość i przydaje życiu smak! Jezus wszystko odwraca. Woda stają się winem!<br>
Po pierwsze proza przechodzi w poezję wielobarwność i rozmaitość.
Po drugie niepokój ustępuje pokojowi, który płynie z przekonania o obecności Jezusa - dawcy Pokoju.
Po trzecie patrzenie na świat przez pryzmat powinności rozszerza się o perspektywę wolności, której spełnieniem jest miłość (myślą przewodnią życia staje się dewiza: działam, bo tak chcę, a chcę, bo kocham).
Po czwarte ludzka niezdolność do działania i słabość przywołują Boże działanie i (wszech)moc.
Po piąte izolacja i zamknięcie się w sobie ustaje, a obecność ludzi staje się źródłem pociechy i wzajemnego zrozumienia.
Po szóste śmierć widziana jest w perspektywie Nieba i stanowi drzwi do szczęśliwej wieczności, do której Bóg nas zaprasza.
Jezus działa i czyni cud(a)! Pan rozwiązuje problemy i wybawia z opresji!
W scenie cudu w Kanie Galilejskiej mamy również zapowiedź dwóch życiodajnych kanałów Łaski Bożej - sakramentów. Woda przywodzi na myśl Chrzest Święty, a wino Eucharystię.<br>
A zatem Pan, którego spotykamy w Kanie Galilejskiej - używając do cudu wody - przypomina nam arcyważny moment w życiu, którym był nasz pierwszy sakrament, czyli Chrzest Święty. Pamiętamy, że gdy Jezus przyjmował chrzest w Jordanie, otworzyło się Niebo i dał się słyszeć głos Ojca: „«Tyś jest mój Syn umiłowany, w Tobie mam upodobanie»" (Mk 1,11). To, co wtedy usłyszał Pan, jest wspaniałym darem także dla nas. Przecież w Jezusie - jednorodzonym Synu Bożym - wszyscy jesteśmy Dziećmi Bożymi - córkami i synami Ojca Niebieskiego!<br>
Tajemnica Chrztu Świętego otwiera więc przed nami ocean MIŁOŚCI, w którym Bóg nas zanurza! Jezus nieprzerwanie powtarza: „Wypłyń na głębię!" (Łk 5,5). I choć sakrament Chrztu przyjęliśmy tylko raz, potrzebujemy ciągle odwoływać się do pierwszego Zanurzenia greckie słówko <i>baptisma</i>, które tłumaczymy jako „chrzest", oznacza dosłownie zanurzenie - niejako wchodzić do chrzcielnicy i ciągle odnawiać w sobie dary, które otrzymaliśmy na progu życia z Jezusem. Kiedyś natknąłem się na ciekawą modlitwę-wiersz dominikanina ojca Kaliksta Suszyło: „Daj mi, Panie Boże, żyć jeszcze troszeczkę, ponieważ jeszcze nie jestem do końca ochrzczony. Woda chrzcielna jeszcze nie dotarła wszędzie, gdzie dotrzeć powinna. Jeszcze we mnie jest dużo starego poganina" (T. Kwiecień, 2005, s.192).<br>
Wino z Kany Galilejskiej zapowiada Eucharystię - ucztę MIŁOŚCI. Jezus umiera za nas na krzyżu, czyli oddaje za nas życie i zarazem daje nam swoje życie. Czyni to z MIŁOŚCI. Ojcowie Kościoła wyrażają to sentencją: <i>Oblatus</i> <i>est,</i> <i>quia</i> <i>voluit</i> 
(łac. <i>Został ofiarowany (ofiarował się), ponieważ sam chciał</i>). Ofiara Ciała i Krwi Pana jest treścią Eucharystii. Jezus ustanawia Najświętszy z sakramentów właśnie właśnie po to, żebyśmy mieli dostęp do Życia i posilali się Komunią Świętą - Ciałem i Krwią Pańską. Życie w Komunii Świętej uświęca nas, napełnia Bogiem, czyni podobnymi do Niego. Komunia Święta pogłębia naszą więź (przyjaźń) z Jezusem. Ojcowie Kościoła piszą, że dzięki udziałowi w Ciele i Krwi Jezusa stajemy się jakby współ-cieleśni i współ-krewni z Jezusem! Cudowna intuicja! Oto wielka tajemnica wiary! W Komunii Świętej między Jezusem a chrześcijanami tworzy więź na kształt małżeństwa! Nie ma większej bliskości jak trwanie w Komunii z Panem! Co więcej, jedność z Ciałem i Krwią Jezusa stanowi zaporę wobec inwazji złych duchów! To dlatego wobec duchowych trudności pokus czy wewnętrznych ciemności możemy śmiało wołać do Pana, aby zasłonił nas swoim Ciałem i swoją Krwią! Jaki to skarb!<br>
Rodzi się pytanie, co możemy (z)robić, żeby Jezus dokonał cudownych przemian w naszym życiu? Odpowiedź z jednej strony jest prosta - wystarczy (za)wołać: „JEZU!". Z drugiej strony trudna, bo aby to wołanie przyniosło owoc, nasza modlitwa musi płynąć z głębokiej wiary, potężnej nadziei i ogromnej miłości do Boga.<br>
W duchowym skarbcu Kościoła znajdujemy modlitwę Jezusową. Jest to nieprzerwane wołanie skierowane do Jezusa miłosiernego. Najbardziej znana formuła modlitwy Jezusowej brzmi: „Panie Jezu Chryste! Synu Boga żyjącego! Zmiłuj się nad mną, grzesznikiem!!!". Możemy do rąk brać różaniec i codziennie - przesuwając palce po paciorkach - wołać z Maryją do Jezusa: Panie Jezu Chryste! Zmiłuj się nade mną! Panie Jezu Chryste! Zmiłuj się nade mną! Panie Jezu Chryste! Panie Jezu! JEZU! Z-MIŁUJ się nade mną!<br?
Św. Filip Neri, który przypisywał Maryi dzieło powstania Oratorium, często powtarzał swoim uczniom: Czcijcie Maryję! Wiem, co mówię!<br>
<b>Lektura duchowa</b>
<i>„Wybrani są ulegli i posłuszni Najświętszej Dziewicy, swej ukochanej Matce, na wzór Jezusa Chrystusa, który z trzydziestu trzech lat, przeżytych na ziemi, poświęcił trzydzieści, by przez doskonałe i całkowite posłuszeństwo swej świętej Matce wielbić Boga, swego Ojca. Są Jej posłuszni i postępują dokładnie według Jej wskazówek, jak młody Jakub wobec Rebeki, gdy do niego rzekła: Synu mój, posłuchaj mego polecenia (Rdz 27,8), lub jak słudzy na godach w Kanie Galilejskiej, do których Najświętsza Dziewica zwróciła się ze słowami: Zróbcie wszystko, cokolwiek wam powie (J 2,5). Dzięki temu, że był posłuszny Matce, Jakub otrzymał błogosławieństwo w sposób zaiste cudowny, jakkolwiek naturalnym biegiem rzeczy nie powinien był go otrzymać. Podobnie słudzy w Kanie Galilejskiej, co usłuchali Najświętszej Dziewicy, dostąpili zaszczytu ujrzenia pierwszego cudu Jezusa Chrystusa, który na prośbę Matki Najświętszej przemienił wodę w wino. Tak samo wszyscy, którzy do końca czasów otrzymywać będą błogosławieństwo Ojca Niebieskiego i będą godni cudów łask Bożych, otrzymają je wyłącznie dla doskonałego posłuszeństwa wobec Maryi".</i>
św. Ludwik Maria Grignion de Montfort, <i>Traktat o prawdziwym nabożeństwie do Najświętszej Maryi Panny</i>, 198<br>
<b>Zadanie</b>
Zaproszę Pana Jezusa do natrudniejszych sytuacji mojego życia z prośbą, aby je przemienił swoją wszechmocną <b>MIŁOŚCIĄ.</b><br>`;

static trescDzien6: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Pana Jezusa, spotkania z Nim w tajemnicy Ukrzyżowania i odkrycia, że Pan przychodzi do mnie w doświadzceniu krzyża i ciepienia, a przez triumf nad śmiercią daje nam udział w swoim Zmartwychwstaniu.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„A obok krzyża Jezusowego stały: Matka Jego i siostra Matki Jego, Maria, żona Kleofasa, i Maria Magdalena. Kiedy więc Jezus ujrzał Matkę i stojącego obok Niej ucznia, którego miłował, rzekł do Matki: «Niewiasto, oto syn Twój». Następnie rzekł do ucznia: «Oto Matka twoja». I od tej godziny uczeń wziął Ją do siebie"</i> (J 19,25-27).<br>
<b>Rozważanie</b>
Jest Wielki Piątek. Zbliża się trzecia po południu. Jezus umiera na krzyżu. Pan oddaje swoje życie za nas. Zaraz pęknie Niebo. Pod krzyżem są najbliżsi Jezusa: Maryja wraz z kobietami, które towarzyszyły Jezusowi w drodze oraz Jan apostoł. Kto wierzy, że w umęczonym Jezusie, którego Ciało jest jedną wielką raną, mieszka Bóg? Kto wierzy, że Bóg w szaleństwie miłości 
„nawet swojego Syna nie oszczędził, ale Go za nas wszystkich wydał" (Rz 8,32)? Maryja wierzy. Dlatego jest pod krzyżem. I pokazuje nam Jezusa jako Pana i Króla, który - choć wszystkim prześladowcom i oprawcom wydaje się, że nie może zrobić nic - może zrobić wszystko! Ukrzyżowany jest Królem królów i Panem panów!<br>
Na krzyżu Jezus walczy. Jest kuszony: „Ci zaś, którzy przechodzili obok, przeklinali Go i potrząsali głowami, mówiąc: «Ty, który burzysz przybytek i w trzy dni go odbudowujesz, wybaw sam siebie; jeśli jesteś Synem Bożym, zejdź z krzyża!»" (Mt 27,39-40). Umiera. Ale agonia Jezusa (w języku greckim słówko <i>agon</i> oznacza walkę, pojedynek) zaczyna się już w Getsemani (grecką nazwę określającą Ogród Oliwny można przetłumaczyć jako „tłocznia oliwy"). To właśnie tam Pan doświadcza trwogi i udręki. W Getsemani Jezus modli się: „«Abba, Ojcze, dla Ciebie wszystko jest możliwe, zabierz ten kielich ode Mnie. Lecz nie to, co Ja chcę, ale to, co Ty [niech się stanie]»" (Mk 14,36). Dramatyczna modlitwa Jezusa ujawnia obecność i krzyżowanie się w Jezusie dwóch natur: ludzkiej i Bożej. Człowiek woła: Chcę żyć! („zabierz ten kielich ode Mnie"), ale Bóg jest gotów oddać życie za ludzkość („lecz nie to, co Ja chcę, ale to, co Ty[niech się stanie]" [Mk 14,36])<br>
Mnisi z zakonu kartuzów powtarzają: <i>Crux</i> <i>stat</i>, <i>dum</i> <i>volvitur</i> orbis (łac. <i>Świat przemija </i>[<i>ziemia się kręci</i>]<i>, a krzyż trwa </i>[<i>stoi</i>]). Jakie to celne i mądre! Wszystko może się zmienić. Jest jednak jedna stała w życiu duchowym. Nazywa się MIŁOŚĆ. Miłość Boga do człowieka, najpełniej wyrażą się w Jezusowym krzyżu. Św. Jan napisał: „Tak bowiem Bóg umiłował świat, że Syna swego Jednorodzonego dał, aby każdy, kto w Niego wierzy, nie zginął, ale miał życie wieczne. Albowiem Bóg nie posłał swego Syna na świat po to, aby świat potępił, ale po to, by świat został przez Niego zbawiony" (J 3,16-17). Bóg nie osądza ani nie oskarża. Pan broni i ocala. I czyni to ciągle. Bo „MIŁOŚĆ nigdy nie ustaje!" (1Kor 13,8a). Nasze życie jest w cieniu Miłości, w cieniu Ukrzyżowanego. Ojcowie Kościoła wyrazili tę prawdę twierdzeniem, że ludzkie życie jest <i>sub</i> <i>crucis</i> <i>sacramento</i> - pod sakramentem krzyża.<br>
Patrzmy na Maryję. Wytrwale stoi pod krzyżem. Zapewne przypomina sobie proroctwo Symeona o mieczu boleści. I nagle słyszy Słowa Syna: „Niewiasto, oto syn Twój" (J 19,27). Patrzy na apostoła Jana, który słyszy: „Oto Matka Twoja" (J 19,28). I uczeń przyjmuje Maryję jako swoją Matkę. To piękny obraz. Często widzimy w Maryi drogę do Jezusa. Wszak Maryja - przez tajemnicę Bożego macierzyństwa - daje nam Jezusa. A zatem zdążamy przez Maryję do Jezusa (łac. <i>Per</i> <i>Mariam ad Iesum)</i>. Ale pod krzyżem to Jezus daje nam Maryję. Jest więc droga odwrotna - zdążamy przez Jezusa do Maryi (łac. <i>Per</i> <i>Iesum</i> ad <i>Mariam</i>)! Pośrednik między Niebem a ziemią obdarowuje nas Maryją i prosi, żebyśmy przyjęli Ją jako Matkę i najpiękniejszy przykład życia!<br>
Umiłowany przez Jezusa apostoł przyjmuje Maryję do siebie - przyswaja sobie Maryjny <i>modus</i> <i>vivendi</i> (łac. <i>styl życia</i>) - model patrzenia i słuchania, poznawania i rozumienia, wartościowania i współodczuwania. Tak Miriam z Nazaretu staje się dla Jana i dla każdego ucznia Jezusa wzorem:<br>
- wiary (łac. <i>stabat</i>). Cztery razy w Biblii pojawia się zdanie: „Sprawiedliwy z wiary żyje (żył będzie)" (zob. Ha 2,4; Rz 10,17; Ga 3,11; Hbr 10,38). I to właśnie wiara sprawia, że pod krzyżem Maryja (prze)żyje i nie umrze. Ona stoi na potężnych nogach wiary. Stoi i nie traci przytomności. Stoi i patrzy na Ukrzyżowanego. Ojcowie Kościoła wyrażali przez wieki przekonanie, że już na Kalwarii Maryja wierzyła, iż śmierć nie zakończy definitywnie ziemskiego życia Jezusa, że Pan zmartwychwstanie (!!!);<br>
- nadziei (łac. <i>fiat</i>). Maryja przez całe życie nosiła w sobie głęboką ufność, że plany Boże się spełnią. Wyraziła to podczas Zwiastowania, gdy powiedziała ochotnym sercem: <i>Fiat</i>! Możemy to przetłumaczyć: „Baaaaardzo chcę, żeby stało się tak, jak chce Bóg!!!";<br>
- miłości (łac. <i>magnificat</i>). Całe życie Miriam z Nazaretu jest utkane z miłości do Boga i do ludzi. Najpiękniej o swoim życiu Maryja opowiada, gdy śpiewa hymn miłości wobec Stwórcy i wdzięczności za wszystkie Boże dzieła: <i>Magnificat</i>! „Wielbi dusza moja Pana i raduje się duch mój w Bogu, moim Zbawcy" (Łk 1,46).<br>
Na Golgocie Jezus objawia się w znaku w („sakramencie") krzyża, który wyraża:<br>
- nieskończoną MIŁOŚĆ Boga - „Jezus „umiłowawszy swoich na świecie, do końca ich umiłował" (J 13,1);<br>
- Boże panowanie nad światem (Królestwo Boże) - „Wypisał też Piłat tytuł winy i kazał go umieścić na krzyżu. A było napisane: «Jezus Nazarejczyk, Król Żydowski»" (J 19,19b) - tak krzyż staje się tronem Jezusa-Króla;<br>
- zwycięstwo Pana nad wszelkim złem - „Jezus skreślił zapis dłużny obciążający nas nakazami. To właśnie, co było naszym przeciwnikiem, usunął z drogi, przygwoździwszy do krzyża. Po rozbrojeniu Zwierzchności i Władz, jawnie wystawił je na widowisko, powiódłszy je dzięki Niemu w triumfie" (Kol 2,14-15).<br>
Nasze życie jest w cieniu krzyża. W bliskości Ukrzyżowanego. Dlatego św. Paweł pisze: „Wam bowiem z łaski dane jest dla Chrystusa: nie tylko w Niego wierzyć, ale i dla Niego cierpieć" (Flp 1,29), a także „Tymczasem ja dla Prawa umarłem przez Prawo, aby żyć dla Boga: razem z Chrystusem zostałem przybity do krzyża. Teraz zaś już nie ja żyję, lecz żyje we mnie Chrystus. Choć nadal prowadzę życie w ciele, jednak obecne życie moje jest życiem wiary w Syna Bożego, który umiłował mnie i samego siebie wydał za mnie" (Ga 2,19-22). To niezwykle mocne Słowa, które kreślą przed nami perspektywę przeżywania każdego cierpienia w bliskości i łączności z Jezusem Ukrzyżowanym.<br>
<b>Lektura duchowa</b>
<i>„Jezus Chrystus, nasz Zbawiciel, prawdziwy Bóg i prawdziwy człowiek, musi być ostatecznym celem wszelkiej naszej pobożności, inaczej byłaby ona fałszywa i zwodnicza. Jezus Chrystus to Alfa i Omega (por. Ap 1,8), początek i koniec wszystkiego (por. Ap 21,16). Pracujemy po to, jak mówi Apostoł, by każdego człowieka uczynić doskonałym w Jezusie Chrystusie (por. Ef 4,13), gdyż tylko w Nim mieszka cała pełnia Bóstwa (por. Kol 2,9) i cała pełnia łaski, cnoty i doskonałości. Tylko w Nim otrzymaliśmy pełnię błogosławieństwa duchowego (por. Ef 1,3). Chrystus jest naszym jedynym Mistrzem, który ma nas nauczać; jedynym Panem, od którego zależymy; jedyną Głową, z którą mamy być zjednoczeni; jedynym Wzorem, do którego mamy się upodobnić; naszym jedynym Lekarzem, który ma nas uzdrowić; jedynym Pasterzem, który ma nas żywić; jedyną Drogą, która ma nas prowadzić; jedyną Prawdą, której musimy wierzyć; jedynym Życiem, które ma nas ożywiać; słowem: jest naszym jedynym Wszystkim we wszystkim, które ma nam wystarczyć. Albowiem nie dano ludziom pod niebem żadnego innego Imienia, w którym moglibyśmy być zbawieni (por. Dz 4,12). (...) Przez Niego, z Nim i w Nim możemy wszystko: możemy oddać Bogu Ojcu w jedności Ducha Świętego wszelką cześć i chwałę; stać się doskonałymi; a dla naszego bliźniego - być miłą wonią Chrystusową na żywot wieczny. Jeśli więc ustanawiamy doskonałe nabożeństwo do Najświętszej Dziewicy, to jedynie po to, by nasze nabożeństwo do Jezusa Chrystusa stało się gruntowniejsze i doskonalsze, oraz by podać łatwy i pewny środek do znalezienia Chrystusa. Gdyby nabożeństwo do Najświętszej Dziewicy oddalało nas od Jezusa Chrystusa, to trzeba by je odrzucić jako złudzenie szatańskie. Tymczasem rzecz ma się przeciwnie, jak to już wykazałem i jeszcze wykażę. Nabożeństwo to jest konieczne, ale po to, by Jezusa Chrystusa całkowicie znaleźć, ukochać Go i wiernie Mu służyć".</i>
św. Ludwik Maria Grignion de Montfort, <i>Traktat o prawdziwym nabożeństwie do Najświętszej Maryi Panny</i>, 61-62<br>
<b>Zadanie</b>
Ofiaruję Bogu przez Serce Maryi wszystkie moje krzyże, cierpienia i udręki, aby zaczerpnąć mocy od Chrystusa.<br>`;

static trescDzien7: string = `<i>Maryjo, Oblubienico Ducha Świętego, wyproś mi łaskę poznania Pana Jezusa, spotkania z Nim w tajemnicy Kościoła i odkrycia, że Pan nieprzerwanie zanurza mnie w miłości Bożej.</i><br><i>Amen!</i><br>
<b>Słowo Boże</b>
<i>„Kiedy nadszedł wreszcie dzień Pięćdziesiątnicy, znajdowali się wszyscy razem na tym samym miejscu. Nagle dał się słyszeć z nieba szum, jakby uderzenie gwałtownego wiatru, i napełnił cały dom, w którym przebywali. Ukazały się im też jakby języki ognia, które się rozdzielały, i na każdym z nich spoczął [jeden]. I wszyscy zostali napełnieni Duchem Świętym, i zaczęli mówić obcymi językami, tak jak im Duch pozwalał mówić"</i> (Dz 2,1-4).<br>
<b>Rozważanie</b>
To dzieje się siedem tygodni po Zmartwychwstaniu Pana. Cały Kościół gromadzi się w Wieczerniku. I przychodzi z Nieba Duch Święty. <i>Parakletos</i> (to imię własne Ducha Świętego można przetłumaczyć: „Posłany, aby był przy nas") jest duszą Kościoła - Ludu Bożego Nowego Przymierza. Duch Święty przynosi miłość łączącą Ojca i Syna. To Duch Jezusa, o którym Pan powiedział, że przypomni apostołom Ewangelię i nauczy wszystkiego (zob. J 14,26). Przyjście Ducha Jezusowego jest dla pierwszej wspólnoty chrześcijańskiej bierzmowaniem - wylaniem darów mądrości, rozumu, rady, umiejętności, męstwa, pobożności i bojaźni Bożej. Kościół otrzymuje potężną (po)moc z Nieba!<br>
Zstąpienie Ducha Świętego to przełom w historii uczennic i uczniów Pana. Siostry i bracia Jezusa czują się jak nowo narodzeni. Właśnie wtedy faryzeusz Nikodem zaczyna rozumieć, co oznaczają Słowa, które powiedział Jezus w nocnej rozmowie: „Zaprawdę, zaprawdę, powiadam ci, jeśli się ktoś nie narodzi z wody i z Ducha, nie może wejść do królestwa Bożego. To, co się z ciała narodziło, jest ciałem, a to, co się z Ducha narodziło, jest duchem. Nie dziw się, że powiedziałem ci: Trzeba wam się powtórnie narodzić. Wiatr wieje tam, gdzie chce, i szum jego słyszysz, lecz nie wiesz, skąd przychodzi i dokąd podąża. Tak jest z każdym, który narodził się z Ducha»" (J 3,5-9).<br>
Duch przychodzi (i jest) jak wiatr. „Nagle dał się słyszeć z nieba szum, jakby uderzenie gwałtownego wiatru, i napełnił cały dom, w którym przebywali" (Dz 2,2). Kościół słyszy oddech Miłości Ojca i Syna. I powstaje echo, które niesie się aż do dziś dnia i nie skończy się. Bo Duch Święty działa i będzie działał na wieki wieków. Ludzie, którzy widzą, co się dzieje, są zdziwieni „Zdumiewali się wszyscy i nie wiedzieli, co myśleć: «Co ma znaczyć?» - mówili jeden do drugiego. «Upili się młodym winem» - drwili inni" (Dz 2,12-13). Jest godzina dziewiąta rano [„trzecia godzina dnia" (Dz 2,15)]. A napełnieni Duchem Świętym uczniowie Jezusa zachowują się tak, jakby byli nietrzeźwi. Dominikanin, o. Jan Góra, napisał kiedyś książkę pt. <i>Pijani Bogiem</i>. Publikacja nawiązuje do doświadczenia Pięćdziesiątnicy. Bo to, co wtedy się zdarzyło, Ojcowie Kościoła określają jako trzeźwe upojenie Duchem Świętym. Fascynujące doznanie! Przeogromny entuzjazm! Euforia! Ekstaza! Pierwsi członkowie wspólnoty czują wszechogarniającą obecność Jezusa, który przychodzi w Duchu Świętym. I wszystko się zmienia. Otrzymują od Pana nowe oczy, nowe uszy, nowe zmysły, nową wrażliwość, nowe serce, nowego ducha, nowe Życie. Nowe wszystko. Już się nie boją.<br>
Zawsze mnie zachwyca i wzrusza to, co pisze św. Łukasz w drugim rozdziale Dziejów Apostolskich. To, co dzieje się z Kościołem w Dniu Pięćdziesiątnicy, owocuje cudami. Święty Piotr zabiera głos i krótkie kazanie sprawia, że do pierwszej wspólnoty, która liczyła mniej więcej 120 osób (zob. Dz 1,15) „przyłączyło się (...) około trzech tysięcy dusz" (Dz 2,41)!!! Jezus, który posyła Ducha Świętego, to sprawia! Jezus żyje w swoim ludzie! Pan żyje w Kościele!<br>
Ciągle się zastanawiam i myślę: Jak to się stało? Co się zdarzyło, że doświadczenie Pięćdziesiątnicy było tak potężne? Dlaczego to przełom w życiu pierwszego Kościoła?<br>
Odpowiedzi kryją się w tekście Dziejów Apostolskich:<br>
1. Są „wszyscy razem". Jakie to cudowne świadectwo! Już w przeddzień Pięćdziesiątnicy Kościół jest cały (scalony), zjednoczony. „Wszyscy (...) trwali jednomyślnie na modlitwie razem z niewiastami, z Maryją, Matką Jezusa, i braćmi Jego" (Dz 1,14).<br>
2. Są „na tym samym miejscu". Co to za miejsce"? To Jezus!!! Są „przy Jezusie", czyli opierają się na Panu - znajdują się wokół Zmartwychwstałego - w przestrzeni Eucharystii - przy Jezusowym Ciele i Krwi.<br>
3. Trwają w bez-ruchu. Potrójną stałość pierwszych uczniów Jezusa Ojcowie Kościoła określają jako <i>stabilitas</i> <i>loci</i> - <i>stałość miejsca</i> (fizycznie są ciągle w jednym miejscu - w Wieczerniku, a metafizycznie dniem i nocą gromadzą się wokół Jezusa); <i>stabilitas</i> <i>mentis</i> - <i>stałość myśli</i>, nieprzerwanie myślą - rozmyślają - medytują o Panu - zgłębiają Słowa obietnicy oraz <i>stabilitas</i> <i>cordis</i> - <i>stałość serca</i>, trwają swoimi sercami nieustannie przy Sercu Jezusa...<br>
4. Noszą w sobie wielkie pragnienie duchowe - pragnienie Ducha Świętego (znów przypomina się Janowa Ewangelia: „W ostatnim zaś, najbardziej uroczystym dniu święta Jezus wstał i zawołał donośnym głosem: «Jeśli ktoś jest spragniony, a wierzy we Mnie - niech przyjdzie do Mnie i pije! Jak rzekło Pismo: Rzeki wody żywej popłyną z jego wnętrza». A powiedział to o Duchu, którego mieli otrzymać wierzący w Niego; Duch bowiem jeszcze nie był ＜dany＞, ponieważ Jezus nie został jeszcze uwielbiony" (J 7,37-39).<br>
Maryja jest w Wieczerniku. Milczy. I czeka. Chłonie Ducha Świętego. Nazwana przez Ojców Kościoła <i>Pneumatofora</i> - <i>Niosąca Ducha</i> - przyjmuje ogień z Nieba. Poprośmy Maryję o doświadczenie Pięćdziesiątnicy - o poczucie przynależności do Kościoła, który jest Ciałem Jezusa; o otwartość na przyjęcie deszczu Łask z Nieba.<br>
Jezus jest w swoim Kościele! Pan żyje w nas! To oznacza, że nas potrzebuje! Tak rodzi się wzajemność! My należymy do Ciała Jezusa, ale i Jezus należy do nas! My żyjemy w Jezusie i dzięki Panu, ale i Jezus żyje w nas! Stajemy się przedłużeniem Jezusowych dłoni i stóp. Żyjąc z Panem i w Panu piszemy nowe stronice Świętej Księgi i stajemy się żywą Ewangelią! Tylko żeby tak się stało, potrzebujemy mocy z wysoka - nowego tchnienia Ducha Świętego! Jezus i dziś chrzci Duchem i ogniem, rozpalając serca swoich przyjaciół! Pan obiecuje, że bramy piekielne nie przemogą Kościoła!<br>
<b>Lektura duchowa</b>
<i>„Oddanie się duszy i ducha Maryi.<br><br>Jeśli będziesz wierny praktykom tego nabożeństwa, dusza Najświętszej Dziewicy zjednoczy się z twoją duszą, by wielbić Pana; ducha twego Jej duch ogarnie, by radować się w Bogu, Zbawicielu swoim. Niech dusza Maryi będzie w każdym człowieku, aby tam wielbić Pana; niech duch Maryi będzie w każdym człowieku, aby radować się w Bogu.<br>
Kiedyż nadejdą owe czasy szczęśliwe - rzekł pewien wielki czciciel Maryi - kiedyż nadejdą owe czasy szczęśliwe, gdy Maryja zostanie ustanowiona Panią i Władczynią serc, by je zupełnie poddać panowaniu wielkiego i jedynego Jezusa? Kiedyż dusze będą tak oddychać Maryją, jak ciało oddycha powietrzem? Wtedy to dopiero staną się cuda na tym padole, kiedy Duch Święty, znajdując swą najdroższą Oblubienicę jakby odzwierciedloną w duszach, zstąpi na nie z całą obfitością i napełni je swymi darami, zwłaszcza darem mądrości, by przez nie dokonywać cudów łaski. Drogi bracie, kiedyż nadejdą owe czasy szczęśliwe, ów wiek Maryi, gdy dusze wybrane i przez Maryję wyproszone u Najwyższego, same się zatracając w otchłani Jej wnętrza, staną się żywymi Jej obrazami, by kochać i wielbić Jezusa Chrystusa? Czasy te nadejdą dopiero wówczas, gdy ludzie poznają i praktykować będą nabożeństwo, którego nauczam: Niech przyjdzie Królestwo Twoje, niech przyjdzie królestwo Maryi".
św. Ludwik Maria Grignion de Montfort, <i>Traktat o prawdziwym nabożeństwie do Najświętszej Maryi Panny</i>, 217<br>
<b>Zadanie</b>
Oddam Maryi wszystkie moje sprawy, całe życie, radości i cierpienia i błagać będę, aby wyprosiła mi przyjście Ducha Świętego z całą mocą, zdolną przemienić moje życie i poprowadzić do swego Syna.<br>`;

static dzien0: string = `${ThirdWeekTexts.tytul} <b>Wprowadzenie</b><br>
<i>Trzeci tydzień poświęcą poznaniu Jezusa Chrystusa</i>".
św. Ludwik Maria Grignion de Montfort, <i>Traktat o prawdziwym nabożeństwie do Najświętszej Maryi Panny</i>, 228<br>
<b>Wprowadzenie</b>
„Chcemy ujrzeć Jezusa!" (J 12,21). Tak kiedyś powiedzieli Grecy, którzy przyszli na Święto Paschy do Jerozolimy i spotkali apostoła Filipa. Mieli w sobie wielkie pragnienie poznania Jezusa. Zapewne nieraz słyszeli o Mistrzu z Nazaretu, który głosił Ewangelię o Królestwie i czynił cuda. Słyszeli, ale nie widzieli Pana. Nie spotkali Jezusa twarzą w twarz. Dlatego szukali...<br>
Mam nadzieję, że pragnienie doświadczenia obecności żywego Jezusa jest również w nas. Głęboko wierzę, że Pan, który zna nasze serca, odpowie na to pragnienie i będzie objawiał swoją twarz na kartach Biblii, a my dzięki fragmentom Ewangelii spotkamy Jezusa i przekonamy się, że przychodzi do nas z różnych stron.<br>
Zatem przed nami droga z(a) Panem. Jesteśmy na początku cudownej przygody. Będziemy - jak pierwsi uczniowie - szli za Jezusem. Dlatego wołamy do Rabbiego z Nazaretu: „«Nauczycielu gdzie mieszkasz?» (J 1,38). Mistrzu! Chcemy być w Twojej szkole! Pragniemy Cię słuchać i patrzyć na Ciebie! (Od)Powiedz nam! Prosimy Cię, Panie! Gdzie jest Twój dom? Gdzie jesteś? Gdzie przebywasz?" W Ewangelii czytamy, że Jezus zwraca się do uczniów i odpowiada: „Chodźcie, a zobaczycie!" (J 1,39). I my dziś to słyszymy...<br>
Na drodze poznawania Jezusa będzie nam towarzyszyła Najświętsza Maryja Panna. Miriam z Nazaretu najpełniej poznała Pana na ziemi. Była i jest zawsze tak bardzo blisko Jezusa. I to nie tylko przez 30 lat ukrytego życia Pana w Nazarecie. Gdy Jezus przez trzy lata prowadzi swoją działalność publiczną, Maryja ciągle jest blisko. Nie jest już obecna w wymiarze fizycznym, ale duchowym. Niemniej silna duchowa więź z Panem oznacza życie w rzeczywistej, prawdziwej i najgłębszej komunii (przyjaźni) z Jezusem. Dlatego Maryja będzie nam pomagała poznawać Pana. Będzie otwierała przed nami wielkie karty Biblii i czytając Słowo Boże, będzie powtarzała, że Ewangelia nie jest przeszłością. To wciąż Dobra Nowina, która może poruszać serca i zachwycać. Ewangelia, którą czytamy i zgłębiamy, dzieje się w nas (w naszym świecie) i jest źródłem poznania Jezusa i przemiany życia! Cuda dzieją się, ponieważ Pan ciągle się objawia i chce być poznawany. A poznany i przyjęty przez nas, działa i czyni w naszym świecie wielkie dzieła...<br>
A więc ruszamy! Wraz z Maryją i przez Maryję (<i>per</i> <i>Mariam</i>) do Jezusa (<i>ad</i> <i>Iesum</i>), aby się powierzyć Panu i oddać całe życie w ręce Boga - Miłości...<br>
Św. Filip Neri zwykł był powtarzać: <i>Nulla</i> dies <i>sine</i> <i>linea! </i>To<i> </i>zdanie<i> </i>w<i> </i>dosłownym<i> </i>tłumaczeniu<i> </i>oznacza<i>: „</i>Nie ma dnia dnia bez kreski". Wielki mistyk XVI w. chciał przez to powiedzieć, że każdego dnia Boży człowiek może zrobić choćby jeden dobry czyn. Bo o Królestwie Bożym nie wystarczy słuchać i opowiadać. To Królestwo możemy każdego dnia urzeczywistniać przez czynienie małego-wielkiego dobra. Wtedy nasza duchowa (niewidzialna) droga z(a) Jezusem staje się cielesna (widzialna) i uzewnętrznia się...<br>
I jeszcze jedna ważna zapowiedź: w duchowej drodze pozna(wa)nia Jezusa w obecności i z pomocą Maryi będzie nam także pomagał św. Ludwik Maria Grignion de Montfort.`;


// bierze stały fragment tytuł rozdziłu dzien podtytuł,dodaje modlitwe do Ducha św, potem bierze tresc danego dnia  i true dodaje modlitwe zawierzenia
static dzien1: string = ThirdWeekTexts.getDayText(1, ThirdWeekTexts.trescDzien1, true);
static dzien2: string = ThirdWeekTexts.getDayText(2, ThirdWeekTexts.trescDzien2, true);
static dzien3: string = ThirdWeekTexts.getDayText(3, ThirdWeekTexts.trescDzien3, true);
static dzien4: string = ThirdWeekTexts.getDayText(4, ThirdWeekTexts.trescDzien4, true);
static dzien5: string = ThirdWeekTexts.getDayText(5, ThirdWeekTexts.trescDzien5, true);
static dzien6: string = ThirdWeekTexts.getDayText(6, ThirdWeekTexts.trescDzien6, true);
static dzien7: string = ThirdWeekTexts.getDayText(7, ThirdWeekTexts.trescDzien7, true);
}